### ISSUE TITLE
Installer Details Missing a Few Things...

### ISSUE THREAD

**Issue by dalponis** [leecher1337/ntvdmx64#1]
Your installer needs some work.

I had to install C++ 2015 x64/x86...

There was no W:\binaries so I had to just manually move all files to release\dos...

And after reboot applications still won't run, they error out just as they always has.

**Comment by leecher1337** [comment]
1) Build instructions work fine for me on Windows XP 32bit. Installer .bat file worked in my Win 10 64bit VDM too. Can you specify which problems occur to you?

2) The loader scripts are written with VC++ 2015, that's correct. However the repository already contains prebuilt .DLLs in the release-subdirectory, so you don't necessarily need to build them on your own if you do not want to. Files in repo are the ones thta work for me.

3) Which OS did you try to build on? As said, I tried on XP 32bit and there it worked for me.

4) Did you check if ldntvdm.dll gets injected into every process properly or at east into explorer.exe after reboot? Did you use prebuilt .dlls from this package for testing? 
If is does not get loaded into processes (you can check with process exlorer), there may be limitations like an active "secure boot" which I think gets used automatically for UEFI boot on raw machines. I think I just had MBR-Boot machines to test yet where it works flawlessly. You can try to turn secure boot off, if this prevents the DLLs from loading (https://msdn.microsoft.com/en-us/windows/hardware/commercialize/manufacture/desktop/disabling-secure-boot).
If DLLs get loaded, they usually print out error information via OutputDebugString(), so you can use DbgView to capture their output (maybe injections into other processes fail on your version?)

**Comment by benreben** [comment]
Hi Leecher1337,

first thx for your work, is an very good idea to reborn ntvdm in 64bit.

but i think the problem @dalponis  is your tutorial... in your point 1) b) the path is **nt**\public\sdk

regards

**Comment by benreben** [comment]
Sorry after long compiling same problem files is not in binaries only autoexec and config.nt
compiling on xp 32bit

**Comment by benreben** [comment]
sorry after long compile i have same error. at last mkrelease have 7 files not found (ntvdm include).

compil on virtual machine xp32bit

**Comment by leecher1337** [comment]
I think I found out the cause... The kernel32.lib needs to be adjusted for window 10, as RegisterConsoleVDM funtion takes a different number of parameters there.. The reason why I fell for this is that I alwways copied by (already sane) SDK directory over during testing instead of extracting it again assuming that it only contains SD stuff and not the lib files, oops :)
Will work on a patch and deploy it shortly, meanwhile sorry for the inconvenience caused

**Comment by benreben** [comment]
have test on windows 7 64 bits and don't work too.
in waiting of tour patch...
thx

**Comment by leecher1337** [comment]
Patch commited, hopefully it works now.

**Comment by leecher1337** [comment]
No comment has been posted, so I assume this can be considered fixed.
