### ISSUE TITLE
Can Not Install on Windows 10 Professional 64Bit.

### ISSUE THREAD

**Issue by rileyil77** [leecher1337/ntvdmx64#101]
So, I've installed using the binary files found here:  http://www.columbia.edu/~em36/ntvdmx64.html

I installed once or twice and was getting this error:

![NTVDMx64 - Install Error](https://user-images.githubusercontent.com/36186391/89317629-3e9f4680-d643-11ea-9378-52a47383bfeb.jpg)

Then it would give me this:

![NTVDMx64 - Install Completed](https://user-images.githubusercontent.com/36186391/89317929-b3728080-d643-11ea-9229-83ce8878bd14.jpg)

After it still didn't work I reached out to a friend in California, who has it working, on nearly the same laptop that I have.  We tried together 3 times.  I own ProBoard Bulletin Board System software, and was going to test the latest version in a Windows 64Bit environment, but every time I go to run PROCFG.EXE of the ProBoard BBS software, I was getting this:

![PB - Running ProCFG](https://user-images.githubusercontent.com/36186391/89318325-40b5d500-d644-11ea-9777-b0495a2fe57a.jpg)
![PB - Error](https://user-images.githubusercontent.com/36186391/89318355-4c090080-d644-11ea-9c0d-b5a8e3c0f9de.jpg)

Here is my system and OS Information:

![OS - Info](https://user-images.githubusercontent.com/36186391/89318416-6347ee00-d644-11ea-933e-9787b15083d5.jpg)
[SLASHTOP - CPU-Z HTML report file.pdf](https://github.com/leecher1337/ntvdmx64/files/5023265/SLASHTOP.-.CPU-Z.HTML.report.file.pdf)

Please help me.  I've been a Computer Tech Hardware guy for 30 years...  This is a first one for me.  But again, I'm not a programmer, I have a great team that does that work for me.  All donating their time.  Thanks again, for your time and what you've done for the community.  This should have been including with Windows 64Bit to begin with.  Thanks again.

John Riley

**Comment by leecher1337** [comment]
Hi,

Do you get a dialog asking "Do you want to install WOW32 (Win16 application) support?" prior to the error message?
WOW32 support is not needed for DOS-only applications, just 16bit Windows applications (where WineVDM is a better choice anyway).

Did you check your Antivirus program if it eliminated the ldntvdm.dll loaders? Unfortunately, the 32bit loader is always detected as a Virus false-positive and therefore Windows Defender etc. tend to remove it or even deny access to the loader .dll files.
To check, if the loaders are present or install them manually:

Copy 
ntvdmpatch\release\ldntvdm\syswow64\10.0\ldntvdm.dll -> C:\windows\syswow64\
ntvdmpatch\release\ldntvdm\system32\10.0\ldntvdm.dll -> C:\windows\system32\

I recommend using the latest loaders from this repository, as I recently fixed a bad handle leak bug.
If antivirus cries, ensure to tell it to leave the loader alone and permanently accept the files on the system. 
Then also ensure that the loader is installed in AppInit and that AppInit is allowed. 

Run 
ntvdmpatch\release\reg\appinit.reg
ntvdmpatch\release\reg\ldntvdm.reg

To install the AppInit hooks for the loader.
This in short describes the manual loader installation process in case the rest of the installation process for installing the ntvdm-files in your System32 and Syswow64 directories worked.

**Comment by rileyil77** [comment]
Leecher1337,

I actually shut-off Avast (my anti-virus) during the install.  I will print
this message out and see if these steps work.

Thanks for your quick response and help,

John Riley

**Comment by rileyil77** [comment]
Leecher1337,

Using the files you said to use fixed my issue!  Thanks again, for your time and effort!

John Riley
http://proboardbbs.com
ProBoard BBS Software (Open Sourced - February 2019, The Day I Bought ProBoard.)
Make ProBoard the Choice of Professionals Again!
