### ISSUE TITLE
Is it real ?

### ISSUE THREAD

**Issue by peter8777555** [leecher1337/ntvdmx64#104]
Windows XP SP1 + Server 2003 source code has apparently leaked

https://kiwifarms.net/threads/windows-xp-sp1-server-2003-source-code-has-apparently-leaked.76736/?__cf_chl_jschl_tk__=cb1ba4d025d4612d5b21ea749fb2f83cc167b3fe-1601054302-0-AbqsNRs1TSgIxp8ZMjvZJHoJdHulAB3uimxh2ts0W3yDBiHBwTdrOOOVbI6xlFERU53MkMvOKqor1GMnsP1Pt0yYDVGV_k_qFt0ruvhVT4ltmNLCTJF3JoM3Jc2r_j5gTk6LIG7Q3LqpZXWDn6ThXrFiJwSTXPNan93mgMcCeacOC9lbQOXsxy6valtKEJUQ3SNb2FAuSda61IXJIz1vgb-Nm4B6c-5L0HT9Xy7jz6Omgfj5eOjUTj10CzQXxm1I8lPVVLF52fXVd3F8LyP-SSZRqaaDRBGShWgW2BzkAl2BSRoUNjaAy2Z4rpmBJbwISH7I6DcB9vlOE1TkbpLrfwgaFTk6Ojl5d1yrNgpH-GzKl_kn30Y3YLyC1Kt1snL4dw

**Comment by leecher1337** [comment]
Seems so, I also read the news, but minnt build already is basically Windows XP NTVDM. WOW16 from it could be interesting, though, because minnt build is lacking it, so only NT4 WOW16 was known and I invested quite some time into patching NT4 wow16 to work with minnt build.

**Comment by peter8777555** [comment]
Thank you for info.
