### ISSUE TITLE
Include a portable version of 7-zip

### ISSUE THREAD

**Issue by kristibektashi** [leecher1337/ntvdmx64#109]
Although it is a useful utility and most people probably have it installed, it's a good idea to include the portable version (https://www.7-zip.org/a/7z1900-extra.7z) (32-bit version recommended) as a fallback in case someone doesn't have it installed.

**Comment by leecher1337** [comment]
From the readme:
```
7za.exe features:

  - High compression ratio in 7z format
  - Supported formats:
      - Packing / unpacking: 7z, xz, ZIP, GZIP, BZIP2 and TAR 
      - Unpacking only: Z, lzma, CAB.
```

That's not enough, we also need support for .iso etc.
