### ISSUE TITLE
install.bat

### ISSUE THREAD

**Issue by agentxan** [leecher1337/ntvdmx64#111]
The entries added by install.bat to defender were added as

"C:\WINDOWS\system32\ldntvdm.dl
"C:\WINDOWS\syswow64\ldntvdm.dll

Defender still flagged them. I think there is an extra " in the commands

I changed "DefExclusion="%SystemRoot%\system32\ldntvdm.dll" to "DefExclusion=%SystemRoot%\system32\ldntvdm.dll" 
and "DefExclusion="%SystemRoot%\syswow64\ldntvdm.dll" to "DefExclusion=%SystemRoot%\syswow64\ldntvdm.dll"

This then works fine and the entries were added as

C:\WINDOWS\system32\ldntvdm.dl
C:\WINDOWS\syswow64\ldntvdm.dll

 and defender does not detect a problem

**Comment by AngryDavid808** [comment]
Looks like a simple mistake in the code inside the file. No biggie. Hope @leecher1337 sees it.

**Comment by leecher1337** [comment]
Thank you for your report. I guess with commit above, it can be considered fixed, therefore I close this issue.
