### ISSUE TITLE
Does it support Windows 10 on ARM?

### ISSUE THREAD

**Issue by kristibektashi** [leecher1337/ntvdmx64#118]
Considering Windows 10 on ARM also uses Syswow64 to emulate x86, it should work

**Comment by leecher1337** [comment]
I don't have an ARM machine with Windows, so I guess you need to try it yourself.
NTOSBE generally seems to have arm suport from what I read (environment var SIZ_NTARCH).
So let me know about your findings.

**Comment by kristibektashi** [comment]
@leecher1337 I just realized that even if it works I won't be able to actually use it since there is no ARM version of the ldntvdm.dll that is required in order to actually launch DOS applications

**Comment by leecher1337** [comment]
Yes, ldntvdm source is available, but you may need to heavily modify it, as it uses x86/x64 asm for patching and process injection.
And I don't know if all the NTVDM-facilities that are required from KERNEL32.DLL are also present on arm builds.

**Comment by leecher1337** [comment]
Unable to fulfill request for ARM build due to lack of machine, closing this ticket. If OP wants to try to port it, fork project an submit pull request.
