### ISSUE TITLE
Error Server 2019

### ISSUE THREAD

**Issue by Esongeson** [leecher1337/ntvdmx64#120]
Hi

I know 2019 isnt officially supported, I have ntvdmx64 running my 16-bit application sucessfully in Server 2012R2 and thought I would try 2019. This is in a Hyper-V VM gen2 with secure boot disabled. The 2012R2 i a gen1 non-UEFI if that might make a difference. Anyway getting this error when running install.bat:

Åtkomst nekad=access denied

![image](https://user-images.githubusercontent.com/76178095/108774767-5f3bd900-7560-11eb-9e54-771f7519496d.png)

**Comment by leecher1337** [comment]
Iirc, I installed latest release on Windows Server 2019 successfully, so it should theoretically work.
As you are getting an access denied message on installing WOW32 support (DOS support may still work, if just WOW32 isn't installing, I guess?), you may want to check the file that cannot be written with Sysinternals Process Monitor.
Maybe files that need to be replaced are locked by access permissions or another process is using them.

Of course, Antivirus applications are also bad boys that can prevent access to files, but I guess you don't have any of this snakeoil on your Server machine anyway ;-)

**Comment by Esongeson** [comment]
Thank you for the reply, Im going to check with process monitor

**Comment by leecher1337** [comment]
No feedback has been given on this isse for 9 months, closing.
