### ISSUE TITLE
Hebrew Tutor

### ISSUE THREAD

**Issue by Biblicus** [leecher1337/ntvdmx64#121]
Hebrew Tutor is a 1995 program written for Windows 3.1.  I tried it in Windows 10 64 bit as a test.  When I started the setup file, Windows would not recognize it. I tried command prompt and the program started to install.  The install progress meter went to 90% and stopped.  There were two messages. The first one said debug.  The second said ntvdm error.  I already know there is a problem in the transliteration file. It is a true type font that is not compatible. 

The program does work in dosbox, but I would find it an easier process to start it directly in Windows 10.  The company that sold it is no longer in business. I don't know which files you would need to check. 

Thank you.

**Comment by leecher1337** [comment]
If program doesn't run right away, try to reboot after NTVDMx64  installation so that loader gets injected into explorer.exe
With the new patch referenced, application should run now:

![image](https://user-images.githubusercontent.com/6495842/110999429-a8719280-8380-11eb-9a9c-1fcd65ac29ba.png)

**Comment by Biblicus** [comment]
Hi; 

Thank you for your help.   I am getting back to the Hebrew Tutor program. Where do I access the patch? 

Donald Young

Sent from Mail for Windows 10

**Comment by leecher1337** [comment]
Hi, the easierst way to always build the newest version is the autobuild script:
https://github.com/leecher1337/ntvdmx64/blob/master/ntvdmpatch/doc/autobuild.txt

Just google the prerequisites, put all stuff in a directory and let the build script run.

**Comment by Biblicus** [comment]
I tried the autobuild script.  It completed successfully. I then ran the install.bat file in the release subfolder (c:/ntdvmBLD/w:/ntdvmpatch/release/install.bat). There was a message "Trying to download necessary debug symbols."  Nothing further happens.
Do I meed the OpenNT Project Build also? It did not finish.  There was a problem with the IDW tools not being found.

**Comment by leecher1337** [comment]
Sounds OK to me. 
How long did you wait for the Symbol download? Depending on your Internet connection speed, this might take a few moments.
Normally, the ldntvdm-Loader also downlaods the symbols on first run, but I added Symbol download to the installer so that Symbols get loaded already on installation to speed up the first run.
It is not strictly necessary, so you can edit install.bat to skip this step, but normally, Symbol download should succeed after a few minutes.

**Comment by Biblicus** [comment]
Another problem.  I realized i don't have a releases subdirectory, so I decided to try again and note what is happening.  i am having trouble getting ntvdmx64.zip.  There is a ntvdmx64-master.zip file, but the autobuild wants a ntvdmx64.zip file.  The autobuild has this error. Please see  the screen print enclosed.
[NTVDMx64 download.docx](https://github.com/leecher1337/ntvdmx64/files/6266394/NTVDMx64.download.docx)
[NTVDMx64 download.docx](https://github.com/leecher1337/ntvdmx64/files/6266399/NTVDMx64.download.docx)

**Comment by leecher1337** [comment]
Seems like dwnl.exe is missing in your autobuild-directory?

**Comment by Biblicus** [comment]
Hebrew Tutor is now working.  I remembered I had installed the version of NTVDMx64 that Mr. Mendelson has.  I reinstalled it and then uninstalled it which removed everything.  I did have to set Hebrew Tutor to 640 x 480  screen resolution so it would work. 
The program runs from the CD. The install only sets up shortcuts to the CD.
 
The mtb30run.exe in the INTRO folder loads “contents.tbk” to start the program.  I tried copying the program to the hard disk to run it without the CD, but “contents.tbk” won’t work.  I don’t know if it is copy protected.  It would be great to be able to run the program directly from the hard disk.

Once again, thank you for all the effort in getting a 16 bit program to work in a 64 bit Windows 10.

Donald Young 

Sent from Mail for Windows 10

**Comment by leecher1337** [comment]
Iirc, I downloaded https://archive.org/details/allesveta_gmail_20180621 and then copied HEBTUTOR to C:\ and finally started C:\HEBTUTOR\INTRO\HT.EXE and it ran fine.
Starting ```MTB30RUN.EXE CONTENTS.TBK``` on commandline also worked for me.

Glad it works for you now. :-)

**Comment by emendelson** [comment]
I've posted the 26 March 2021 build  here:

http://www.columbia.edu/~em36/ntvdmx64.html

**Comment by Biblicus** [comment]
Thank you for the latest build.  The program still has a minor issue.  The chapter objectives page opens, but nothing appears on the page for chapter 1: alphabet, chapter 2 vowels and chapter 3 nouns.  The index section opens, but there is only one listing. 

One larger issue is that nothing works for chapter 5: Construct Nouns, or Chapter 6: Qa[ Perfects.
 
I suspect that some of the *.tbk files may not be loading properly.  The trouble is not the Hebrew Tutor program, because these sections do load properly in Windows XP.  Are there one or more programming code features still missing? 

It may not be worth the trouble trying to determine what is needed.

**Comment by leecher1337** [comment]
I can confirm that problem with the Chapter Objectives, I will have a look at it why this isn't displayed.

As for Chapter 5 and Chapter 6, it seems I cannot test this, because the copy on archive.org that I used is indeed missing these 2 chapters (the directories in the copy simply aren't present at all).
If you have these missing chapters on your installation media, you may want to drop me an e-mail, maybe you can send the missing chapters to me from your installation media so that I can test.

**Comment by Biblicus** [comment]
I don't know how to attach the two missing chapters since the files are unsupported types.  I do have them. The Hebrew Tutor (and Greek Tutor) for DosBos is available at <<https://biblicalelearning.org>>.  Go to Intro and Languages. Go to Greek/Hebrew.  Select Hebrew and Greek Tutors - Hildebrandt.  Dr. Hildebrandt is the original author and freely distributes the two programs.  There is an .*iso file that has the Hebrew Tutor within the zip file.  Chapters 5 and 6 are there. 
Thank you for your willingness to work further on getting the program to work in Windows 10.
