### ISSUE TITLE
SSH

### ISSUE THREAD

**Issue by Tonda102** [leecher1337/ntvdmx64#122]
Is it possible to use this in SSH? I tried to launch Norton Commander in SSH but it responded with the "Program nc.exe is not compatible...." error.

**Comment by leecher1337** [comment]
SSH on Windows? I guess it depends how the SSH-daemon works, I didn't try if loader also works in a running service, which SSH daemon do you use so that I can try?

**Comment by Tonda102** [comment]
I use OpenSSH. Client is bundled with Powershell since Fall Creators Update. Server could be installed easily using "optional features" in settings.

**Comment by Tonda102** [comment]
I've also noticed that same problem occurs in Windows Terminal

**Comment by Tonda102** [comment]
Ok. I think that I've figured it out. NTVDM won't run under anything but cmd and Powershell in legacy mode. It seems like cmd in OpenSSH will never run in legacy mode probably bacause of the UTF-8 character encoding. Windows Terminal does the same.

**Comment by leecher1337** [comment]
The reason why it doesn't start in OpenSSH is that ldntvdm.dll loader doesn't get injected into spawned cmd.exe process.
You can test it and inject c:\windows\system32\ldntvdm.dll into the spawned cmd.exe with i.e. Process Hacker (right click on cmd.exe process -> Miscellaneous -> Inject DLL...).
You will be able to start streaming I/O DOS Applications then, but i.e. textmode UI applications will fail, as all the Windows console integration requierd isn't mapped to the SSH daemon and so I guess it won't be of much use.
If this would be usable anyway, I can try to find out how to inject loader into spawned cmd.exe process, but if it's not really useful anyway, I may not put much work into it.
Here is dpmi.exe test program running in an OpenSSH-Session:

![image](https://user-images.githubusercontent.com/6495842/111556880-dc3b2680-878b-11eb-8da1-6d2e460e15c1.png)

**Comment by Tonda102** [comment]
Thank you for your professional explanation! I was originally looking for some universal software that would integrate emulation for original DOS textmode UI applications into modern Windows shell. That's how I ended up here. I personally would not have any real use from the loader so I think that you don't have to really do anything about this.

I really like your work anyway. Wish you the best.

**Comment by leecher1337** [comment]
Just a note: If you don't mind running Linux and you want to use DOS-applications remotely via SSH, I would suggest dosemu, see: https://github.com/leecher1337/ntvdmx64/issues/49
It works really well and fast for this purpose and has the same performance as original NTVDM when running in V86 mode. 
I also made some drivers for dosemu, i.e. Pervasive BTRIEVE driver.
dosemu2 also support KVM integration, so you also have good performance with VT-x.
