### ISSUE TITLE
Btrieve.exe file not found

### ISSUE THREAD

**Issue by Esongeson** [leecher1337/ntvdmx64#124]
![image](https://user-images.githubusercontent.com/76178095/112193593-547c6e80-8c08-11eb-8603-6c767565ef48.png)

Getting three file not found when launching Btrieve.exe, the old record manager software. It seems to load ok anyway but Im getting some issues in some .bat files using btrieve that the operations stop and the cmd-window stays open.

Anyone know of issues that might occur when programs except to find old files like autoexec, config.nt and himem.sys in C:\windows\system32 but cant access them there. I have to place them instead in C:\users\username\windows\system32. Not sure if thats the way it is in newer operating systems like 2012R2 that Im running or if its because Im running this server with the RDS server role.

**Comment by Esongeson** [comment]
Found the reasons for the file not found. It was not affecting the btrieve itself. It was command.com calling autotexec.nt and that contained referenced to files that didnt exist, dosx and msdex and one more. Removed that and the error went away.  I  think my bat-files stopping in the middle is more of a timing issue.

**Comment by leecher1337** [comment]
Hm, these files should exist in a correct NTVDM installation, however they may need to be specified by full path.
In my autoexec.nt, there are the lines:

```
lh %SystemRoot%\system32\mscdexnt.exe
lh %SystemRoot%\system32\redir
lh %SystemRoot%\system32\dosx
```
If dosx doesn't get loaded on start, this may result in lockup of programs that require DPMI, maybe this is the issue.
Can you verify the presence of these files in the SysWOW64 directory (and hard links to these files in system32 directory),
just to be sure?

**Comment by leecher1337** [comment]
There used to be a problem introduced in newer Win10 versions that caused odd behaviour on execution of .bat files, but that was already fixed, I don't think that your loaders are that old, if you did a fresh build:

https://github.com/leecher1337/ntvdmx64/commit/ef9d5c1e35fbce6182c93f0886ec5a0019e5e459

**Comment by leecher1337** [comment]
No comment for more than 9 months, closing the issue now.
