### ISSUE TITLE
cab files fail to expand with autobuild

### ISSUE THREAD

**Issue by Lannuked** [leecher1337/ntvdmx64#129]
When using autobuild, I get this error 

> expand: unknown option -- F
Try 'expand --help' for more information.
Cannot expand _umpdddi.lib_00315 from work\WDK\wxplibs_x86fre_cab001.cab.
Cannot continue.

I would also like to mention that, every time the build fails, it adds a fake drive inside of my drives list, which stays there until a reboot.
![image](https://user-images.githubusercontent.com/26724236/117337203-18753400-ae6b-11eb-82a0-7b720afcc7c0.png)

**Comment by leecher1337** [comment]
subst drive can be removed with ```subst w: /D```
Quoting the docs:

```
if directory path length exceeds 30 characters, a virtual SUBST drive letter is created.
To avoid this step, use a build directory with a very short path name,
i.e. C:\NTVDMBLD
```

So I would recommend to make a build directory near the root level to avoid these problems
i.e. C:\NTVDMBLD as suggested by the documentation.

**Comment by Nukley** [comment]
That fixed the drive issue, but it still is giving me the same problem with cab files

**Comment by Nukley** [comment]
Er, wait, let me clean out the build folder

**Comment by Nukley** [comment]
nope, same issue

**Comment by leecher1337** [comment]
Hm, I don't know an expand version that doesn't support the -F switch. My guess is that you have a program called "expand" in your search path that isn't the Microsoft cabinet expansion tool but some other tool by the same name.
expand.exe normally resides in Windows\System32 folder.
You can try to find the offending program with this command:

`for %i in (expand.exe) do @echo.   %~$PATH:i`

Which output do you get?

**Comment by Nukley** [comment]
Seems to have compiled, but I got this error at least twice 
![image](https://user-images.githubusercontent.com/26724236/117934093-4b3a8480-b2d0-11eb-8c2f-24f5e00fc0f3.png)

**Comment by leecher1337** [comment]
May be a problem with your symbosl, check loader output with DebugView upon start of application.

**Comment by Nukley** [comment]
Like this?
![image](https://user-images.githubusercontent.com/26724236/118185220-4b3e9f80-b40a-11eb-8142-7b2cd0df48c8.png)

**Comment by InterSyncz** [comment]
I haven't installed it yet btw, just compiled it, the error came up during compilation.

**Comment by leecher1337** [comment]
Ah, ok, during compilation, so running exe2bin is not your test case then, as I assumed.

This is a PATH issue then, the SDK ships with a WIN32 version of exe2bin, however, if exe2bin.exe is in your Windows\system32 path, it may get precedence. As the real exe2bin is a DOS program, it cannot run (until NTVDMx64 is installed).
As exe2bin gets reinstalled with NTVDMx64 too, you can just delete it from your system32 directory and retry compilation.

**Comment by leecher1337** [comment]
No further update was given on the ticket, assuming ticket is solved by deleting exe2bin.exe in system32 directory.
