### ISSUE TITLE
DLLs loaded in every single application?

### ISSUE THREAD

**Issue by Rufis01** [leecher1337/ntvdmx64#13]
Does idntvdm.dll get injected in every single application running on windows? I'm worried that some game's anticheat systems could think I am cheating and possibly ban me (?)

**Comment by leecher1337** [comment]
Yes, except if it is a debugee. However this would be a very dumb form of anticheat detection. For example, Windows Shim engine also modifies IAT pointers in executables for instance, so this is quite a normal form of interception. 
But I cannot tell you how applications will react to it, of course.
