### ISSUE TITLE
work on amd64?????

### ISSUE THREAD

**Issue by hdfsyu** [leecher1337/ntvdmx64#134]
DOES THIS WORK ON AMD64 BECAUSE WHEN I RUN A MS-BOB SETUP IT JUST SAYS ITS NOT COMPATIBLE WITH X64!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! (I rebooted when I was done installing)

**Comment by leecher1337** [comment]
![image](https://user-images.githubusercontent.com/6495842/121582736-a5de1200-ca2f-11eb-8a56-b317c69a6b21.png)

Setup runs fine here, check loader output with DebugView

**Comment by leecher1337** [comment]
However, I still suggest using winevdm (otvdm) for Win16, as it's more mature than NTVDMx64's WOW32 support. winevdm (for Win16) and NTVDMx64 (for DOS) can be installed at the same time.

**Comment by hdfsyu** [comment]
ahhhhhhhhhhh so I install otvdm with NTVDM? Good idea just tried that and the setup rolled fine! It even has audio support!

**Comment by hdfsyu** [comment]
k thanks 😄
