### ISSUE TITLE
another stupid issue

### ISSUE THREAD

**Issue by hdfsyu** [leecher1337/ntvdmx64#135]
so clearly in enderman's video he ran windows 1.0 on windows 10 so 2 things 1 WHERE DID HE GET THE FILES FROM!? and 2 when I ran the windows 1 setup installed it to a custom path ran win.com it doesnt work.

**Comment by hdfsyu** [comment]
I hate my amd64 computer

**Comment by leecher1337** [comment]
I tried with NTVDMx64 and it worked (Tested on Win7 x64 using latest NTVDMx64).
1) Download Windows disk images from https://winworldpc.com/download/70cc3f64-f438-11e8-9b71-fa163e9022f0
2) I used 7zip for unpacking disk images and install. What I did was the following:
 a) Create directory, i.e. c:\TEMP\INSTW10
 b) Extract disk1.img with 7zip to C:\TEMP\INSTW10
 c) subst a: C:\TEMP\INSTW10
 d) A:\SETUP.EXE
 e) Tell setup to Install to i.e. C:\WIN10
 f) When it prompts for the next disk, delete contents of C:\TEMP\INSTW10 and extract next disk to it, then continue setup, until you installe dall disks
3) Run WIN.COM in C:\WIN10 
If you get an error about not being able to open the COM port, click ignore, as it tries to find the mouse and possibly cannot.

Althoug practically useless, it's indeed a funny experiment ;-)

**Comment by hdfsyu** [comment]
so u said "win7" ok uh im on windows 10 and enderman actually launched it... I will respond back to u if it works...

**Comment by hdfsyu** [comment]
so I tried and basically the setup went fine until I put in the last disk I put it in and after a few seconds the setup crashed! So I ran win.com from admin cmd prompt (and file explorer) and in cmd it just showed a blank screen then gave the the C:\WIN10 prompt in file explorer it just crashed since im a dev I got an idea for running windows 1.0 on my pc then doing something else with it... Btw it did not even ask for a com port am I supposed to run the setup via the admin cmd prompt?

**Comment by hdfsyu** [comment]
wait- I just realized ur the owner of this project... Sorry if im disturbing u

**Comment by leecher1337** [comment]
Also works fine on Win10, of course:

![image](https://user-images.githubusercontent.com/6495842/121805215-8111b680-cc4a-11eb-9008-c68488635095.png)


As Display adapter during setup, you should choose:
3: IBM Personal System/2 Model Display Adapter Card or Display Adapter 8514/A

It's also enough to unpack all disks into one directory, do a 
subst a: .
and just press continue when it prompts for the next disk. Maybe you can avoid the crash this way.
It only asks for COM port, if you selected a mouse during setup, that's why I mentioned it.

**Comment by hdfsyu** [comment]
> Also works fine on Win10, of course:
> 
> ![image](https://user-images.githubusercontent.com/6495842/121805215-8111b680-cc4a-11eb-9008-c68488635095.png)
> 
> As Display adapter during setup, you should choose:
> 3: IBM Personal System/2 Model Display Adapter Card or Display Adapter 8514/A
> 
> It's also enough to unpack all disks into one directory, do a
> subst a: .
> and just press continue when it prompts for the next disk. Maybe you can avoid the crash this way.
> It only asks for COM port, if you selected a mouse during setup, that's why I mentioned it.

OOOOOOOOOOOOOOOOOOOOOO ok so looks like doing it from admin cmd prompt (and doing display adapter) actually finished the setup and it said this: "Microsoft Windows is setup to operate on ur computer" so yay! But I typed win.com in admin cmd and it just did the same thing showed a blank screen then said C:\WIN10 again. So im thinking this is because im on 64-Bit?

**Comment by hdfsyu** [comment]
and on file explorer it just hangs

**Comment by hdfsyu** [comment]
I unpacked all the floppys using powerISO trial

**Comment by leecher1337** [comment]
Hard to tell why it doesn't work for you.
We can compare files in install directory:
```
04.06.1985  09:07                42 ABC.TXT
11.05.1987  15:24                 0 APPS
11.08.1986  12:02                 8 BUILD.LBL
11.03.1987  09:55            26 496 CALC.EXE
22.05.1986  07:55            37 552 CALENDAR.EXE
22.05.1986  04:23            36 992 CARDFILE.EXE
02.04.1987  11:27            12 016 CITOH.DRV
22.05.1986  06:17             9 712 CLIPBRD.EXE
22.05.1986  06:08             7 984 CLOCK.EXE
26.01.1987  12:52             4 863 COMM.DRV
16.03.1987  17:13            52 736 CONTROL.EXE
02.04.1987  11:27            12 304 COURB.FON
02.04.1987  11:27             8 784 COURC.FON
02.04.1987  11:27            15 136 COURD.FON
02.04.1987  11:27             7 872 COURE.FON
31.03.1987  09:51             4 649 DENMARK.DRV
25.10.1985  13:02               493 DOTHIS.TXT
30.07.1985  17:33            12 874 EMM.AT
30.07.1985  17:15            12 898 EMM.PC
02.04.1987  11:27            14 352 EPSON.DRV
02.04.1987  11:27            12 176 EPSONMX.DRV
31.03.1987  09:51             4 773 FRANCE.DRV
22.05.1986  10:48             1 961 FTG.DRV
09.04.1987  11:40            93 502 GDI.EXE
31.03.1987  09:51             4 758 GERMANY.DRV
02.04.1987  11:27            37 680 HELVB.FON
02.04.1987  11:27            26 624 HELVC.FON
02.04.1987  11:27            45 600 HELVD.FON
02.04.1987  11:27            24 944 HELVE.FON
29.07.1986  16:42             7 472 HIFONTS.FON
02.04.1987  11:27            16 336 HP7470A.DRV
02.04.1987  11:27            72 064 HPPCL.DRV
02.04.1987  11:27            12 288 IBMGRX.DRV
09.04.1987  11:59             2 766 IBMMOUSE.DRV
16.03.1987  16:55            13 952 IBMPS230.DRV
09.03.1987  15:27                14 IBMPS230.GRB
09.03.1987  15:26                14 IBMPS230.LGO
30.03.1987  11:25            17 536 IBMPS250.DRV
16.07.1986  23:07             1 266 IBMPS250.GRB
30.03.1987  11:39             2 943 IBMPS250.LGO
11.03.1987  14:50            17 536 IBMPS2DA.DRV
09.03.1987  15:28                14 IBMPS2DA.GRB
09.03.1987  15:25                14 IBMPS2DA.LGO
31.03.1987  09:51             4 027 ITALY.DRV
22.05.1986  10:35             2 114 JOYMOUSE.DRV
07.04.1987  17:40            34 111 KERNEL.EXE
02.05.1986  17:47             2 661 LMOUSE.DRV
29.07.1986  16:42             5 552 LOFONTS.FON
22.05.1986  10:41             2 438 LPC.DRV
02.04.1987  11:27             7 584 MODERN.FON
24.04.1987  16:13             3 360 MOUSE.DRV
13.06.2021  13:22                 1 MSDOS.EXE
23.06.1986  14:32             6 242 MSDOSD.EXE
22.05.1986  10:45             1 966 MSMOUSE1.DRV
22.05.1986  10:45             1 966 MSMOUSE2.DRV
02.04.1987  11:27            22 512 NEC3550.DRV
02.04.1987  11:27            12 304 NECP2.DRV
22.05.1986  10:42             1 592 NOMOUSE.DRV
31.03.1987  09:51             4 649 NORWAY.DRV
22.05.1986  06:28            18 736 NOTEPAD.EXE
02.04.1987  11:27            12 416 OKI92.DRV
11.05.1987  14:35            90 512 PAINT.EXE
13.06.2021  13:17    <DIR>          PIF
09.09.1985  15:04             2 944 PRACTICE.WRI
02.04.1987  11:27           112 752 PSCRIPT.DRV
01.08.1986  05:59             6 680 RAMDRIVE.SYS
07.04.1987  17:57            10 455 README.TXT
11.03.1987  10:15            15 392 REVERSI.EXE
02.04.1987  11:27            11 120 ROMAN.FON
29.05.1987  15:30            36 646 SETUP.EXE
11.08.1986  11:59                 8 SETUP.LBL
02.04.1987  11:27            14 848 SG10.DRV
22.05.1986  11:49             5 853 SOUND.DRV
31.03.1987  09:51             4 630 SPAIN.DRV
08.04.1987  19:53            13 360 SPOOLER.EXE
31.03.1987  09:51             4 649 SWEDEN.DRV
09.07.1986  15:15             2 663 SYSTEM.DRV
12.06.1986  11:22            47 344 TERMINAL.EXE
02.04.1987  11:27            12 128 THINKJET.DRV
02.04.1987  11:27            11 584 TI850.DRV
02.04.1987  11:27            36 240 TMSRB.FON
02.04.1987  11:27            25 824 TMSRC.FON
02.04.1987  11:27            45 200 TMSRD.FON
02.04.1987  11:27            23 968 TMSRE.FON
02.04.1987  11:27            12 432 TOSH.DRV
02.04.1987  11:27             4 800 TTY.DRV
31.03.1987  09:51             4 009 UK.DRV
31.03.1987  09:50             4 005 USA.DRV
08.04.1987  20:19           122 848 USER.EXE
02.04.1987  11:27                11 UTILITY.LBL
12.11.1985  16:13             1 936 WIN.CNF
07.04.1987  17:40             4 879 WIN.COM
13.06.2021  13:22             2 198 WIN.INI
07.04.1987  17:40           183 504 WIN100.BIN
07.04.1987  17:40           219 312 WIN100.OVL
16.07.1986  23:07             1 266 WINOLDAP.GRB
01.08.1986  03:16            19 824 WINOLDAP.MOD
08.05.1987  10:00           192 176 WRITE.EXE
02.04.1987  11:27            21 024 XER4020.DRV
```

Contents of win.ini:
```
; this is a comment, i.e. a line preceded by a semicolon
; comments should NOT contain an equal sign

[windows]
; Set spooler to no to prevent loading of spooler
spooler=yes
DoubleClickSpeed=500
CursorBlinkRate=550
; Programs entry determines which file extensions are displayed
; by DOS executive View Program command
; pif might also be an extension to add
programs=com exe bat
; NullPort entry determines the string used to denote the "null" port
; for connections, see control panel's Set Connections command
NullPort=None
; Load entry specifies what applications should be loaded as icons
load=
; Run entry specifies what applications should be run.  Use comma to
; start a new column of tiled applications, e.g. two columns.  Also
; notice that an application may be preloaded, e.g. dothis.txt starts
; NOTEPAD.EXE.
run=

[extensions]
cal=calendar.exe ^.cal
crd=cardfile.exe ^.crd
trm=terminal.exe ^.trm
txt=notepad.exe ^.txt
ini=notepad.exe ^.ini
msp=paint.exe ^.msp
wri=write.exe ^.wri
doc=write.exe ^.doc

[colors]

[pif]
swapdisk=?
swapsize=0
assign.com=1
attrib.exe=32
backup.com=64
chkdsk.com=64
command.com=32
comp.com=64
diskcomp.com=64
diskcopy.com=64
edlin.com=64
find.exe=64
join.exe=20
mode.com=1
more.com=64
print.com=1
recover.com=64
restore.com=64
sort.exe=64
subst.exe=20
win.com=1

[intl]
iCountry=43
iDate=1
iCurrency=2
iDigits=2
iTime=1
iLzero=0
s1159=
s2359=
sCurrency=S
sThousand=.
sDecimal=,
sDate=.
sTime=:
sList=,
dialog=yes

[ports]
; To output to a file make an entry in this section of the form
; filename.PRN followed by an equal sign.
; The filename will appear in the Control Panel Connections dialog and
; any printer may then be connected to this file and all printing will
; be done to this file. 
EPT:=
LPT1:=
LPT2:=
LPT3:=
COM1:=1200,n,8,1
COM2:=1200,n,8,1

[fonts]
Courier 8,10,12 (Set #6)=COURE
Helv 8,10,12 (Set #6)=HELVE
Tms Rmn 8,10,12 (Set #6)=TMSRE
Courier 8,10,12 (Set #5)=COURD
Helv 8,10,12 (Set #5)=HELVD
Tms Rmn 8,10,12 (Set #5)=TMSRD
Roman (Set #1)=ROMAN
Modern (Set #1)=MODERN
System, Terminal (Set #3)=HIFONTS
System, Terminal (Set #2)=LOFONTS
```

Same with your installation?

**Comment by hdfsyu** [comment]
> Hard to tell why it doesn't work for you.
> We can compare files in install directory:
> 
> ```
> 04.06.1985  09:07                42 ABC.TXT
> 11.05.1987  15:24                 0 APPS
> 11.08.1986  12:02                 8 BUILD.LBL
> 11.03.1987  09:55            26 496 CALC.EXE
> 22.05.1986  07:55            37 552 CALENDAR.EXE
> 22.05.1986  04:23            36 992 CARDFILE.EXE
> 02.04.1987  11:27            12 016 CITOH.DRV
> 22.05.1986  06:17             9 712 CLIPBRD.EXE
> 22.05.1986  06:08             7 984 CLOCK.EXE
> 26.01.1987  12:52             4 863 COMM.DRV
> 16.03.1987  17:13            52 736 CONTROL.EXE
> 02.04.1987  11:27            12 304 COURB.FON
> 02.04.1987  11:27             8 784 COURC.FON
> 02.04.1987  11:27            15 136 COURD.FON
> 02.04.1987  11:27             7 872 COURE.FON
> 31.03.1987  09:51             4 649 DENMARK.DRV
> 25.10.1985  13:02               493 DOTHIS.TXT
> 30.07.1985  17:33            12 874 EMM.AT
> 30.07.1985  17:15            12 898 EMM.PC
> 02.04.1987  11:27            14 352 EPSON.DRV
> 02.04.1987  11:27            12 176 EPSONMX.DRV
> 31.03.1987  09:51             4 773 FRANCE.DRV
> 22.05.1986  10:48             1 961 FTG.DRV
> 09.04.1987  11:40            93 502 GDI.EXE
> 31.03.1987  09:51             4 758 GERMANY.DRV
> 02.04.1987  11:27            37 680 HELVB.FON
> 02.04.1987  11:27            26 624 HELVC.FON
> 02.04.1987  11:27            45 600 HELVD.FON
> 02.04.1987  11:27            24 944 HELVE.FON
> 29.07.1986  16:42             7 472 HIFONTS.FON
> 02.04.1987  11:27            16 336 HP7470A.DRV
> 02.04.1987  11:27            72 064 HPPCL.DRV
> 02.04.1987  11:27            12 288 IBMGRX.DRV
> 09.04.1987  11:59             2 766 IBMMOUSE.DRV
> 16.03.1987  16:55            13 952 IBMPS230.DRV
> 09.03.1987  15:27                14 IBMPS230.GRB
> 09.03.1987  15:26                14 IBMPS230.LGO
> 30.03.1987  11:25            17 536 IBMPS250.DRV
> 16.07.1986  23:07             1 266 IBMPS250.GRB
> 30.03.1987  11:39             2 943 IBMPS250.LGO
> 11.03.1987  14:50            17 536 IBMPS2DA.DRV
> 09.03.1987  15:28                14 IBMPS2DA.GRB
> 09.03.1987  15:25                14 IBMPS2DA.LGO
> 31.03.1987  09:51             4 027 ITALY.DRV
> 22.05.1986  10:35             2 114 JOYMOUSE.DRV
> 07.04.1987  17:40            34 111 KERNEL.EXE
> 02.05.1986  17:47             2 661 LMOUSE.DRV
> 29.07.1986  16:42             5 552 LOFONTS.FON
> 22.05.1986  10:41             2 438 LPC.DRV
> 02.04.1987  11:27             7 584 MODERN.FON
> 24.04.1987  16:13             3 360 MOUSE.DRV
> 13.06.2021  13:22                 1 MSDOS.EXE
> 23.06.1986  14:32             6 242 MSDOSD.EXE
> 22.05.1986  10:45             1 966 MSMOUSE1.DRV
> 22.05.1986  10:45             1 966 MSMOUSE2.DRV
> 02.04.1987  11:27            22 512 NEC3550.DRV
> 02.04.1987  11:27            12 304 NECP2.DRV
> 22.05.1986  10:42             1 592 NOMOUSE.DRV
> 31.03.1987  09:51             4 649 NORWAY.DRV
> 22.05.1986  06:28            18 736 NOTEPAD.EXE
> 02.04.1987  11:27            12 416 OKI92.DRV
> 11.05.1987  14:35            90 512 PAINT.EXE
> 13.06.2021  13:17    <DIR>          PIF
> 09.09.1985  15:04             2 944 PRACTICE.WRI
> 02.04.1987  11:27           112 752 PSCRIPT.DRV
> 01.08.1986  05:59             6 680 RAMDRIVE.SYS
> 07.04.1987  17:57            10 455 README.TXT
> 11.03.1987  10:15            15 392 REVERSI.EXE
> 02.04.1987  11:27            11 120 ROMAN.FON
> 29.05.1987  15:30            36 646 SETUP.EXE
> 11.08.1986  11:59                 8 SETUP.LBL
> 02.04.1987  11:27            14 848 SG10.DRV
> 22.05.1986  11:49             5 853 SOUND.DRV
> 31.03.1987  09:51             4 630 SPAIN.DRV
> 08.04.1987  19:53            13 360 SPOOLER.EXE
> 31.03.1987  09:51             4 649 SWEDEN.DRV
> 09.07.1986  15:15             2 663 SYSTEM.DRV
> 12.06.1986  11:22            47 344 TERMINAL.EXE
> 02.04.1987  11:27            12 128 THINKJET.DRV
> 02.04.1987  11:27            11 584 TI850.DRV
> 02.04.1987  11:27            36 240 TMSRB.FON
> 02.04.1987  11:27            25 824 TMSRC.FON
> 02.04.1987  11:27            45 200 TMSRD.FON
> 02.04.1987  11:27            23 968 TMSRE.FON
> 02.04.1987  11:27            12 432 TOSH.DRV
> 02.04.1987  11:27             4 800 TTY.DRV
> 31.03.1987  09:51             4 009 UK.DRV
> 31.03.1987  09:50             4 005 USA.DRV
> 08.04.1987  20:19           122 848 USER.EXE
> 02.04.1987  11:27                11 UTILITY.LBL
> 12.11.1985  16:13             1 936 WIN.CNF
> 07.04.1987  17:40             4 879 WIN.COM
> 13.06.2021  13:22             2 198 WIN.INI
> 07.04.1987  17:40           183 504 WIN100.BIN
> 07.04.1987  17:40           219 312 WIN100.OVL
> 16.07.1986  23:07             1 266 WINOLDAP.GRB
> 01.08.1986  03:16            19 824 WINOLDAP.MOD
> 08.05.1987  10:00           192 176 WRITE.EXE
> 02.04.1987  11:27            21 024 XER4020.DRV
> ```
> 
> Contents of win.ini:
> 
> ```
> ; this is a comment, i.e. a line preceded by a semicolon
> ; comments should NOT contain an equal sign
> 
> [windows]
> ; Set spooler to no to prevent loading of spooler
> spooler=yes
> DoubleClickSpeed=500
> CursorBlinkRate=550
> ; Programs entry determines which file extensions are displayed
> ; by DOS executive View Program command
> ; pif might also be an extension to add
> programs=com exe bat
> ; NullPort entry determines the string used to denote the "null" port
> ; for connections, see control panel's Set Connections command
> NullPort=None
> ; Load entry specifies what applications should be loaded as icons
> load=
> ; Run entry specifies what applications should be run.  Use comma to
> ; start a new column of tiled applications, e.g. two columns.  Also
> ; notice that an application may be preloaded, e.g. dothis.txt starts
> ; NOTEPAD.EXE.
> run=
> 
> [extensions]
> cal=calendar.exe ^.cal
> crd=cardfile.exe ^.crd
> trm=terminal.exe ^.trm
> txt=notepad.exe ^.txt
> ini=notepad.exe ^.ini
> msp=paint.exe ^.msp
> wri=write.exe ^.wri
> doc=write.exe ^.doc
> 
> [colors]
> 
> [pif]
> swapdisk=?
> swapsize=0
> assign.com=1
> attrib.exe=32
> backup.com=64
> chkdsk.com=64
> command.com=32
> comp.com=64
> diskcomp.com=64
> diskcopy.com=64
> edlin.com=64
> find.exe=64
> join.exe=20
> mode.com=1
> more.com=64
> print.com=1
> recover.com=64
> restore.com=64
> sort.exe=64
> subst.exe=20
> win.com=1
> 
> [intl]
> iCountry=43
> iDate=1
> iCurrency=2
> iDigits=2
> iTime=1
> iLzero=0
> s1159=
> s2359=
> sCurrency=S
> sThousand=.
> sDecimal=,
> sDate=.
> sTime=:
> sList=,
> dialog=yes
> 
> [ports]
> ; To output to a file make an entry in this section of the form
> ; filename.PRN followed by an equal sign.
> ; The filename will appear in the Control Panel Connections dialog and
> ; any printer may then be connected to this file and all printing will
> ; be done to this file. 
> EPT:=
> LPT1:=
> LPT2:=
> LPT3:=
> COM1:=1200,n,8,1
> COM2:=1200,n,8,1
> 
> [fonts]
> Courier 8,10,12 (Set #6)=COURE
> Helv 8,10,12 (Set #6)=HELVE
> Tms Rmn 8,10,12 (Set #6)=TMSRE
> Courier 8,10,12 (Set #5)=COURD
> Helv 8,10,12 (Set #5)=HELVD
> Tms Rmn 8,10,12 (Set #5)=TMSRD
> Roman (Set #1)=ROMAN
> Modern (Set #1)=MODERN
> System, Terminal (Set #3)=HIFONTS
> System, Terminal (Set #2)=LOFONTS
> ```
> 
> Same with your installation?

uh yeah (to make sure I copied ur win.ini file into mine) and guess what IT WORKED! Ok im joking lol it doesnt work still does same thing...

**Comment by hdfsyu** [comment]
the funny thing is we are the only ones commenting XD

**Comment by hdfsyu** [comment]
I guess this is cuz of hardware 🤷🏻

**Comment by hdfsyu** [comment]
@leecher1337

**Comment by leecher1337** [comment]
What should I tell you? I already showed you my testing results.

**Comment by hdfsyu** [comment]
I am closing this issue, due to lack of response
