### ISSUE TITLE
Old CAD system issues

### ISSUE THREAD

**Issue by G-Rumpel** [leecher1337/ntvdmx64#138]
Hi,
I use an old CAD system called OrCAD which consists of graphical tools for schematic and PCB design, digital simulations  etc.
Generally it does work under NTVDMx64 with a few small glitches I will try to explain.
There is a main process which starts a graphical environment with buttons:

![image](https://user-images.githubusercontent.com/84896182/122683040-88fec700-d205-11eb-87e4-89c6c382f8ec.png)

Each button starts a different tool or a chain of tools which processes data/files forth and back the system i.e. the one's output is transformed and supplied as an input to the next etc.  The problem arises when I try to start two different tools one after the other. Then the following error appears:

![image](https://user-images.githubusercontent.com/84896182/122683328-2a3a4d00-d207-11eb-8a55-45c0ba343f28.png)

Secondly every tool/chain generates a report in the form of a text file which is opened in a text editor (also 16-bit application). If the tool starts the editor (to see the output) then the previous message appears or there is an error in the output:

![image](https://user-images.githubusercontent.com/84896182/122683618-15f74f80-d209-11eb-8a4c-52698520525b.png)

At the same time all tools work normally if they are started separately (not under the main graphical environment). 
Generally these are 16-bit processes which start other 16-bit processes which is very similar to #28 which should be addressed some time ago. 
Last but not the least the CAD system doesn't start under OTVDM at all so my hopes are to find a solution .
I will be glad to help in any way if possible.
Regards

**Comment by leecher1337** [comment]
Do you have installation media so that I can test?

**Comment by G-Rumpel** [comment]
Hi,
I will prepare a ready to use directory and upload it later.
There will be no need for installation except copying one file to %SYSTEMROOT%\System32.

**Comment by G-Rumpel** [comment]
Hi,
I have prepared a ready to use package some 15 MB in size. It contains the CAD system, a user guide, a GDI driver and instructions how to start it and reproduce the problem. It would be best if I can send it to your "...dose..." email. It is an old but still copyrighted software and I would like not to make it public.
Regards

**Comment by leecher1337** [comment]
Hi,

Ok, will treat it confidentially just for testing.
Just send me a short mail from your e-mail address so that I can instruct you on how
to send it (there is a 10MB size limit on my Mailbox per Mail, iirc).

**Comment by G-Rumpel** [comment]
Hi,
Did you have a time to look at that?
Regards

**Comment by leecher1337** [comment]
I can reproduce the problem, but analysis may be hard as I suspect that the application is using protected mode code. 
May take a few weeks/months, need to find time for it.

**Comment by G-Rumpel** [comment]
OK,
I'll be looking forward to it but I won't disturb you.
Regards

**Comment by leecher1337** [comment]
With latest 2 commits, the problem was fixed on my test machine, no more crashes, can you confirm?

**Comment by G-Rumpel** [comment]
Hi,
First of all, thank you for your efforts and time spent on the subject.
I compiled from the latest commit eb0ec38 and everything looked good. I tested many of the tools and experienced no errors.
So I consider this issue as closed. If anything arises I will report back further.
Once again, thank you very much for keeping this project alive!
Regards!
