### ISSUE TITLE
Error initializing screen while opening apps

### ISSUE THREAD

**Issue by MinecraftW06** [leecher1337/ntvdmx64#139]
I tried to open an msdos app, and it said "Error initializing screen".
What can I do?
![gh](https://user-images.githubusercontent.com/65031582/123232544-8c31d580-d4d9-11eb-9f04-70f575b040f2.PNG)

**Comment by leecher1337** [comment]
Which application are you trying to use?
You can debug the application with your favourite DOS debugger to find out the reason (i.e. Turbo Debugger).
Or you can use NTVDM's debugger YODA to do an instruction trace and check out the code path leading to the message.
Does the application work correctly in 32bit Windows NTVDM?

**Comment by MinecraftW06** [comment]
Works correctly on 32-bit Windows NTVDM.

**Comment by peter8777555** [comment]
MSD works on Windows 7 X64.

![zxc](https://user-images.githubusercontent.com/29886853/123258103-92e63a00-d525-11eb-9f54-51e8ef97e854.png)

**Comment by leecher1337** [comment]
Also works on Win10 x64 here...

![image](https://user-images.githubusercontent.com/6495842/123263692-8cda6400-d4f9-11eb-94a8-d8739a7a5288.png)

**Comment by peter8777555** [comment]
By the way,
I know the new build support OLE 2.0

I check
https://en.wikipedia.org/wiki/Object_Linking_and_Embedding
OLE 2.0 :
New features were OLE automation, drag-and-drop, in-place activation and structured storage.

But i hard to understand OLE 2.0 for CMD console.
Any video for demo ??

**Comment by leecher1337** [comment]
OLE 2.0 is just for WOW32, so for 16bit Windows applications.
NTVDMx64 implementation still is slow and partly buggy, so it's propably not very useful compared with otvdm/winevdm, but for the sake of completeness, it was added anyway.

**Comment by leecher1337** [comment]
No further updates on MSD.EXE issue given, issue not reproducible, assuming it has been solved, reopen ticket on further updates.
