### ISSUE TITLE
w:\ntvdmpatch\util\patch.exe the specified path does not exist

### ISSUE THREAD

**Issue by JanAlthoetmar** [leecher1337/ntvdmx64#15]
Hello,
when I start patch.cmd i receive the following error messsage:

(https://user-images.githubusercontent.com/11482887/34303690-e3e1deea-e736-11e7-8903-7af43a564286.JPG)
In english:
the path doesn't exist.

I've setup w:\ drive as described in you instruction.

Best regards

**Comment by leecher1337** [comment]
Hallo,
Und, liegt die patch.exe dort oder nicht? Im Repository ist sie jedenfalls im angegebenen Pfad drin, also viell. ein Fehler beim Herunterladen des Repositorys?
Btw.: https://github.com/leecher1337/ntvdmx64/issues/7

**Comment by leecher1337** [comment]
Video tutorial for compiling in #18
