### ISSUE TITLE
Some apps are inaccessible and crash when using NTVDMx64 on Windows 11

### ISSUE THREAD

**Issue by Sunlitspace542** [leecher1337/ntvdmx64#151]
Running Windows 11.
After installing a freshly built copy of NTVDMx64 made using autobuild.
Firefox crashes.
Tried to run another app, exe deletes itself.
can't start my antivirus.
and other weirdness,

**Comment by leecher1337** [comment]
Cannot reproduce.
Installed Firefox on clean Windows 11 Version 21H2, Build 22000.194

Are you using builtin Windows Defender or some 3rd party shitty Antivirus solution? 
Maybe Antivirus is runnig havoc crashing the processes the loader injected to? Even Windows Defender always produces false positives on the loader, so other AV solutions may be even worse.
Check stacktrace of crashed application to find location where it crashed and show it.
Also check Debugview output from loader, if you find something that goes wrong with process injection.

![image](https://user-images.githubusercontent.com/6495842/136648197-f795a3b6-63c0-41a7-913c-9b7f960e5710.png)

**Comment by Sunlitspace542** [comment]
I use avast. when NTVDM is installed, it doesn't start at all.

**Comment by Sunlitspace542** [comment]
I attempted a reinstall, didn't work, uninstalled, now apps from the windows store will not start.
![image](https://user-images.githubusercontent.com/35207254/136661075-7db2613a-626b-4c78-bf19-06f48a25b97d.png)

**Comment by Sunlitspace542** [comment]
I managed to get the two apps back up and running again, however WSL gives me this error:
![image](https://user-images.githubusercontent.com/35207254/136661957-d7f16dd8-1ee5-4267-ae89-be34bf696a06.png)

**Comment by Sunlitspace542** [comment]
![image](https://user-images.githubusercontent.com/35207254/136662171-214c6907-bc9b-4ab9-bfb0-8e40d5267350.png)
tried reinstalling, now I get this

**Comment by ringtailedfox** [comment]
> after some fiddling, I got WSL back up and running. closing issue, idk what's wrong with my system that ntvdm doesn't like. I give up.

what did you do to fix WSL2?  i tried installing NTVDMx64 and now WSL2 doesn't even start for me.  uninstalling NTVDMx64 didn't fix it, so i worry i may have to re-install WSL2 and have to reconfigure my entire distro in there..
