### ISSUE TITLE
What about Windows Server 2022?

### ISSUE THREAD

**Issue by kristibektashi** [leecher1337/ntvdmx64#152]
It's a different build than both latest Windows 10 and Windows 11. How well is it supported?

**Comment by leecher1337** [comment]
Not tested yet, I suggest you try it out on non-production machine/VM and report back. 
Windows 11 loader needs some more testing by users anyway, maybe someone can reproduce the problems from #151 (as I cannot reproduce them) and if there are problems, make stack traces from crashed applications to help with analysis (or share VM image where problems are detected).
