### ISSUE TITLE
Breaks after 2021-11 Updates on Win7

### ISSUE THREAD

**Issue by bilditup1** [leecher1337/ntvdmx64#155]
After applying 2021-11 Cumulative (KB5007236) and .NET (KB5007149) Updates on Win7, attempting to run a DOS program results in conhost summarily crashing. This happened on two machines, so does not appear to be a one-off. I have not yet tried with Win10 (the machines have Secure Boot on) and don't have any Win11 builds yet.

**Comment by InterSyncz** [comment]
my conhost just crashes outright, no matter if its a dos program or not, I'm on Windows 10.

**Comment by InterSyncz** [comment]
I copied and renamed my conhost to soup.exe and it works fine.

**Comment by InterSyncz** [comment]
Moving ldntvdm.dll out of my system32 and syswow64 folder fixes the issue

**Comment by leecher1337** [comment]
Problem cannot be reproduced, I installed both updates, no problems with them:

![image](https://user-images.githubusercontent.com/6495842/142554535-41637f63-85d1-4ef4-bf92-a865cec8ae47.png)

Have you tried uninstalling and reinstalling ntvdmx64 after the update? Maybe symbols didn't get updated properly and old offsets are still cached in registry?

**Comment by bilditup1** [comment]
After a couple of reboots I can no longer reproduce either. Did not reinstall, did not touch registry. Very strange.

**Comment by Xanderplayz16** [comment]
Honestly upgrade to windows 10 or 11 7 is unsupported and not many newer programs are compatible.

**Comment by bilditup1** [comment]
This is happening again with the 2022-04 update, on several different machines, summarily crashing and giving the familiar warning about 16-bit applications. This time, rebooting did not help. I uninstalled and reinstalled, same result. Checking the registry, there was an HKLM\Software\ldntvdm key, but there was nothing under it. Under AppInit_DLLs in HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows NT\CurrentVersion\Windows, "ldntvdm.dll" showed up but with a leading space; deleting this space did not help so I put it back in.

**Comment by leecher1337** [comment]
Check debugview output

**Comment by bilditup1** [comment]
...OK, I ran debugview, but now it works. It looks like new symbols were needed, but probably weren't found before? So perhaps they weren't updated until later this week? There are still some 'hooking failed' reports but I successfully ran a 16-bit application. 
![01_ldntvdm_hooking-failed-but-works__2022-04-16](https://user-images.githubusercontent.com/357902/163682657-8986e36a-029b-4889-a9a7-df8f2f59636e.PNG)
[00_ldntvdm_syms-downloaded__2022-04-16.LOG](https://github.com/leecher1337/ntvdmx64/files/8500265/00_ldntvdm_syms-downloaded__2022-04-16.LOG)
[01_ldntvdm_hooking-failed-but-works__2022-04-16.LOG](https://github.com/leecher1337/ntvdmx64/files/8500266/01_ldntvdm_hooking-failed-but-works__2022-04-16.LOG)

**Comment by bilditup1** [comment]
I now suspect that symbols need updating with every subsequent Patch Tuesday, as this is happening again with identical output from dbgview. I don't know if this is a new trend, or if this is inherent and that I just wasn't paying close enough attention to these machines for the 2021-12, 2022-01, 2022-02, and 2022-03 updates.

**Comment by leecher1337** [comment]
It sometimes can take a few days until the symbols appear on symbol server.
See also https://github.com/leecher1337/ntvdmx64/issues/190
So: https://www.youtube.com/watch?v=RNJ9pet2scY

**Comment by leecher1337** [comment]
According to user, symbols were updated: https://github.com/leecher1337/ntvdmx64/issues/190#issuecomment-1123311632

**Comment by bilditup1** [comment]
Yup! Just came back here to say that they do in fact appear to have updated it, I didn't bother checking if it worked again until today. It might be a good idea to put a little warning to this effect regarding symbols and Patch Tuesday kernel32.dll updates on the main page?

**Comment by bilditup1** [comment]
Awesome! Thanks again for all your work on this!
