### ISSUE TITLE
Some programs do not start after installing NTVDMx64

### ISSUE THREAD

**Issue by MrPepka** [leecher1337/ntvdmx64#158]
I am using the autobuild-ccpu-fre.cmd build
The patch compiles, but after installing it and restarting my computer, I cannot run 32-bit programs. Only after uninstalling the patch (sometimes you have to restart the computer after that) these programs start. How can I solve it?

**Comment by leecher1337** [comment]
Did you wait long enough for the debug symbols to download?
Could take a few minutes to download 32bit symbols upon first launch of 32bit application.

**Comment by leecher1337** [comment]
I was able to reproduce it on another machine, hopefully the loader update fixes your issues.

**Comment by MrPepka** [comment]
Thanks, the patch is now working properly
