### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by Houfino** [leecher1337/ntvdmx64#163]
Hi...

I have a small problem..I could not download ... Danger error .... What should I do? thank you 

https://ibb.co/Kxb3L4Z

**Comment by leecher1337** [comment]
Seems NTOSBE got DMCAed, switches to mirror. I strongly encourage every user to make a copy of NTOSBE and keep it so that it can be reuploaded should other mirrors also fail.

https://github.com/github/dmca/blob/master/2022/01/2022-01-06-microsoft-5.md

**Comment by Houfino** [comment]
> Ok..Thank you ... Will Windows 10 64bit work?
 I'll make a copy and hide .... DCMA is bad :-/

**Comment by leecher1337** [comment]
NTVDMx64 works on Windows 10, yes

**Comment by leecher1337** [comment]
As opennt.net domain seems to have expired, use this DNS entry for other build requirements:

`1.214.196.85 file.opennt.net`

It's also good if many people mirror it, so that availability can be ensured in the future

**Comment by Houfino** [comment]
Thank you so much .... It works for me ... I ask and are you going to do for Windows 11 ??? Thank you :-)

**Comment by leecher1337** [comment]
Windows 11 is also supported, at least it works for me with the new loaders introduced in 9d44d45b8bae51e558989bec066cabc6290dc4c2 (with sime minor bugfixes in later commits).

**Comment by Houfino** [comment]
> Windows 11 is also supported, at least it works for me with the new loaders introduced in [9d44d45](https://github.com/leecher1337/ntvdmx64/commit/9d44d45b8bae51e558989bec066cabc6290dc4c2) (with some minor bugfixes in later commits).

Thank you..You really pleased me that Windows 10 works..I prefer to stay Windows 10 .....
Microsoft is bad that it ends up with 16bit support..Thanks for you that you did and it works.... Solved :-)
