### ISSUE TITLE
DPMI Bug

### ISSUE THREAD

**Issue by Valsamon** [leecher1337/ntvdmx64#164]
The DPMI host does not zero extend to EDI the protected mode offset returned in DI if functions 305h and 306h are called by a 32-bit client. AFAIK a 32-bit DPMI client should expect to find the offset in EDI, not just in DI, but the upper word of EDI seems to be preserved across the call instead of being zeroed.

**Comment by leecher1337** [comment]
Thanks for reporting, confirmed with attached test program.
[dpmitst.zip](https://github.com/leecher1337/ntvdmx64/files/7965586/dpmitst.zip)

**Comment by leecher1337** [comment]
No comments have been made within 30 days and a fix was deployed, assuming that issue is resolved with patch, closing.
