### ISSUE TITLE
Program too big to fit in memory

### ISSUE THREAD

**Issue by wrongwrithe3** [leecher1337/ntvdmx64#169]
Steps to produce:
1. Went to [icecat-win64](https://github.com/muslayev/icecat-win64)
2. Followed [readme](https://github.com/muslayev/icecat-win64/blob/master/portable/readme.md)
3. Ran [start.exe](https://github.com/muslayev/icecat-win64/blob/master/portable/start.exe) from %comspec%,%powershell% and Windows Terminal
4. "Program too big to fit in memory" was shown in the programs instead of spawning a new process of icecat.exe from core\icecat.exe

**Comment by leecher1337** [comment]
Not reproducable here. From what you describe, this effect normally occurs if the file you are trying to execute is damaged and not a valid PE file. In this case, it is assumed that it must be a DOS .com file (as .com files have no header, they are just assembly programs that get loaded into memory and executed, can be a maximum of 64k).
Now if you execute a damaged file and the loader tries to execute it as a .com program, it hands it over to NTVDM and DOS sees that its size is over 64k segment limit, thus refusing it to run (leading to "Program too big to fit in memory" error)
So I'd say your start.exe is damaged, check it with a hex editor. Not NTVDM related.

**Comment by wrongwrithe3** [comment]
You're right. Retried and it works now. Just have this one written off as an user error. Closing the issue.
