### ISSUE TITLE
Install.bat fails due to detecting 64-bit installation of Windows 10 as being 32-bit

### ISSUE THREAD

**Issue by Coolie2** [leecher1337/ntvdmx64#170]
As I'm not the biggest fan of the terminal, I was glad to find this option for launching DOS games. Unfortunately, when trying to run the Install.bat file as an administrator, I was told to use the regular version of the utility as it had detected my 64-bit Windows 10 installation as being 32-bit. If there's any log files that may help in figuring out what the issue might be, I'd be glad to upload them!

**Comment by leecher1337** [comment]
You can list the output of the following registry query:
```
reg query HKLM\Hardware\Description\System\CentralProcessor\0
```
Normally, on x86 systems, the "Identifier" subkey begins with  "x86" on a 32bit system.

If you are planning to use NTVDMx64 just for games, you may be disappointed, the CCPU is slow and there is no support for high video resolutions, so you may be better off using dosbox, if it's just for running games.

**Comment by leecher1337** [comment]
No answer given regarding output, closing. If still relevant, reopen.
