### ISSUE TITLE
"Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item."

### ISSUE THREAD

**Issue by Ahmad-Hesham** [leecher1337/ntvdmx64#171]
Hello,

I downloaded a compiled version of ntvdmx64 but whenever I try to access a 16-bit application I get one of the d/m errors.
Without "Run as administrator":
![image](https://user-images.githubusercontent.com/99060519/155275957-6945444c-b767-4104-b4f4-e17d845e7aff.png)
With "Run as administrator":
![image](https://user-images.githubusercontent.com/99060519/155276035-63703085-ec9a-4f1a-8d95-996cdfa08720.png)

What am I doing wrong?

Thanks in advance,

**Comment by leecher1337** [comment]
Iirc, there are some weird "detection" rules based on Filename within Windows that may enforce elevation, even though it may not really be needed. So either:

1) Rename the file to something not containing "STP" in its name
2) Move the file to a location that the elevated user can also access and run it elevated from there.

**Comment by Ahmad-Hesham** [comment]
I formatted the hard drive and performed a clean Windows 11 installation.
ntvdmx64 worked but some functions of a 16-bit application did not work and no errors popped up.
Can you do me a favor and compile the latest version of ntvdmx64 then send it to my e-mail ahmedhesham3@gmail.com? (If you have some time of course)

**Comment by leecher1337** [comment]
What function didn't work? You need to provide full details, if you need help.

Sorry, I cannot compile and send it due to legal reasons. Which problems with compilation do you have? I would need a detailled problem report for your compilation issues as well in order to diagnose them.

**Comment by Ahmad-Hesham** [comment]
Actually I tried two different precompiled versions as the compilation steps were too complicated.
Is there a step-by-step video tutorial for beginners?

**Comment by leecher1337** [comment]
All steps are described in https://github.com/leecher1337/ntvdmx64/blob/master/ntvdmpatch/doc/autobuild.txt
Release-Files for Autobuild: https://github.com/leecher1337/ntvdmx64/releases
It's really easy, just download prereq. files to a directory and run a batch file, I don't think that this is really compilicated. 
Someone also wrote a tutorial even for autobuild, use Google Translate: https://www.planetkode.com/2021/05/tutorial-ntvdmx64-menjalankan-aplikasi.html

**Comment by Ahmad-Hesham** [comment]
Tried the autobuild tutorial and got this.
Please advise
![image](https://user-images.githubusercontent.com/99060519/157693057-4d1312ad-3413-4cd5-804f-0071eb5a4eb8.png)

**Comment by Ahmad-Hesham** [comment]
Thank you for helping me out so far.
But I am still in need for your further help.
After installing ntvdmx64 I tried several 16-bit applications most of them worked properly but there is one Arabic application -that I am trying to get it to work for my father- that's driving me crazy, It works normally on Windows 10 x86 with native ntvdm.
How can I get a report/log for you to investigate?

**Comment by leecher1337** [comment]
Can you describe the error that you are experiencing? Also, which application is it? Can a copy of the application be obtained somewhere in order to test it? That would make things a lot easier, beacuse describing how to debug via the Github Issue tracked would be a tedious task.
Is it a DOS application or a Win16 application?

**Comment by Ahmad-Hesham** [comment]
It does not display any errors it just freezes.
It is some religious application.
It can be obtained here https://ia800301.us.archive.org/0/items/sharawycd/El-Sharawy.iso
It is a Win16 application.

**Comment by leecher1337** [comment]
If it's a Win16 application: Have you tried running it with [https://github.com/otya128/winevdm](winevdm) ?
Some applications work better with WineVDM, some others only work with NTVDMx64. NTVDMx64 gives WineVDM precedence over itself for Win16 application, if WineVDM is installed, when WineVDM gets uninstalled, you are back to NTVDMx64, so it's work trying it out at least.

**Comment by Ahmad-Hesham** [comment]
Oh wow it worked! You and Otya are geniuses, Microsoft should fire their noobs and people like you are supposed to take the helm instead.
The issue is now resolved.
Thank you very much for your effort and time
