### ISSUE TITLE
Fails to install because ansi.sys is missing 

### ISSUE THREAD

**Issue by Xanderplayz16** [leecher1337/ntvdmx64#172]
Windows 11
Dell Inspiron 3080
all files in /dos are gone, including ansi.sys except csrstub. Can you give me a download of the files in /dos or a fixed version?
![Screenshot 1](https://user-images.githubusercontent.com/74632800/155863972-8e07e304-5382-4d9e-ad10-e18654ece647.png)
![Screenshot 2](https://user-images.githubusercontent.com/74632800/155863992-587fb1d0-7fbd-4753-be0a-557e05b64fa8.png)

**Comment by Xanderplayz16** [comment]
Also i dont know how to set up MINNT so i cant use autbuild

**Comment by leecher1337** [comment]
You don't have to set it up, just download it and put it into the autobuild folder as already explained in the documentation:
https://github.com/leecher1337/ntvdmx64/blob/master/ntvdmpatch/doc/autobuild.txt

If you google for the mentioned minnt zip file, you get download links for the build requirements. Alternatively, there also is a hint in https://github.com/leecher1337/ntvdmx64/issues/163

**Comment by Xanderplayz16** [comment]
Oh. Also that installer is amazing!
