### ISSUE TITLE
NTVDMx64 causing issues and crashes for other applications

### ISSUE THREAD

**Issue by BEENNath58** [leecher1337/ntvdmx64#181]
Some applications, such as Windows Widgets or even WhatsApp crash and NTVDM is present in the Event Viewer logs. Can you look into it? Some Event Viewer details down:

```
Fault bucket 1388947968971804227, type 5
Event Name: MoBEX
Response: Not available
Cab Id: 0

Problem signature:
P1: 5319275A.WhatsAppDesktop_2.2208.14.0_x64__cv1g1gvanyjgm
P2: praid:WhatsAppDesktop
P3: 2.2208.14.0
P4: 6192ade3
P5: ldntvdm.dll_unloaded
P6: 0.0.0.0
P7: 60abcbe8
P8: 0000000000003518
P9: c0000005
P10: 0000000000000008
```
 and 

```
Fault bucket 1742458110879191084, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: SppExtComObj.exe
P2: 10.0.22000.318
P3: 1e2c3be0
P4: ldntvdm.dll_unloaded
P5: 0.0.0.0
P6: 60abcbe8
P7: 0000000000003518
P8: c0000005
P9: 0000000000000008
P10: 

```

**Comment by leecher1337** [comment]
Sounds like https://github.com/leecher1337/ntvdmx64/commit/1cc6c7afc796343ff5b5e3417c3a981a510066cf
Are you *absolutely sure* that you are using the latest loaders (dated Mar 7 2022) ?

**Comment by BEENNath58** [comment]
Sorry for the late reply, that might be the cause, I updated it 2 months back last. I'll update you ASAP with the new loader's results.

**Comment by BEENNath58** [comment]
I installed it today and there was no problem in this build. That was it. Thanks.
