### ISSUE TITLE
NTVDMX64 current build fails to work with my BBS fossil driver

### ISSUE THREAD

**Issue by pcmicro** [leecher1337/ntvdmx64#186]
I have written a fossil driver to allow DOS BBS software to run under Windows 32-bit using NTVDM. A few years ago I made a special version named NetFos64 which supports NTVDMX64.  It works fine using older versions of NTVDMX64 that I downloaded from the Columbia University site, but it fails to work with the version that was uploaded to that site in January 2022. The previous build on the Columbia U site was dated 06/06/2021 and this version (and earlier ones) worked fine.

Today I used Autobuild to create the current version of NTVDMX64 but this version also fails to work with NetFos64. 

NetFos64 contains the following components:
NETFOS64.COM  - a DOS TSR that redirects to the DLL
NETFOS64.DLL     - The Win32 Virtual DOS Driver (VDD)
NETCOM.EXE       - The telnet communication engine.

The issue I am seeing is that when the batch file NF64.BAT loads the TSR, the batch file immediately aborts rather then loading the BBS Software. I have tested it with several different DOS BBS software, including ProBoard BBS which is included in the testbed.

You can download the testbed from here: https://pcmicro.com/netfoss/ntvdmx64_bbs_testbed.zip
[Edit: URL typo]

Regards,  Mike

**Comment by leecher1337** [comment]
Hi,

Sorry, I cannot reproduce your problem. I tried with Windows XP 64 and Windows 7 with a build from January 2022.
As soon as I ensure that NETFOS64.DLL is located in Windows\syswow64 directory, it still works as expected for me:

![image](https://user-images.githubusercontent.com/6495842/164801847-661fef25-6120-49fb-8adb-2d9a553681b4.png)

(Otherwise, it fails that it cannot find the DLL, but that's expected behaviour)

**Comment by pcmicro** [comment]
The screen shot you provided shows that the NF64.bat batch file successfully loaded Netfos64, but then the batch file existed to the Command Prompt instead of loading ProBoard BBS as it should have. If ProBoard had loaded, you would see the log-on screen where it asks for a username/password.

My testing was under Windows 10 x64 but it appears to happen in other versions of Windows as well.

**Comment by leecher1337** [comment]
Aha, now I understand, if I do:
```
@echo off
rem do not load ANSI.COM before NetFoss64! 
echo Step 1
c:\netfoss\netfos64.com %1
rem ** If running a DOS based BBS, add " %1" to the end of above line **
if errorlevel 1 goto end
echo Step 2
c:\netfoss\netcom.exe %1 %2 %3 %4 %5 %6 %7 %8 %9
echo Step 3
c:\netfoss\netfos64.com /u
echo Step 4
:end
echo End
```

I get Step1, the driver loiads and then I never get to "Step 2" or "End" but I'm stuck in the ntvdm showing the prompt.
If I abort the NTVDM, script continues (wihtout the TSR). Strange

**Comment by pcmicro** [comment]
I ran autobuild again and the new commit solved the issue. Thanks!

**Comment by pcmicro** [comment]
Today I tested the new NTVDMx64 build under Windows XP x64 SP2, and under this OS the issue is still present!
Yesterday I tested the same build under Windows 10 x64 and there was no issue.

**Comment by leecher1337** [comment]
Interesting, not reproducable here. Using these loaders:
```
C:\Documents and Settings\Administrator>cd \windows\system32

C:\WINDOWS\system32>dir ldntvdm.dll
 Volume in drive C has no label.
 Volume Serial Number is 107E-E1A5

 Directory of C:\WINDOWS\system32

21.04.2022  15:14            63.488 ldntvdm.dll
               1 File(s)         63.488 bytes
               0 Dir(s)  33.533.849.600 bytes free

C:\WINDOWS\system32>cd ..\SysWOW64

C:\WINDOWS\SysWOW64>dir ldntvdm.dll
 Volume in drive C has no label.
 Volume Serial Number is 107E-E1A5

 Directory of C:\WINDOWS\SysWOW64

05.03.2022  14:06            50.688 ldntvdm.dll
               1 File(s)         50.688 bytes
               0 Dir(s)  33.533.849.600 bytes free

C:\WINDOWS\SysWOW64>
```

Test was a .cmd file that loaded NETFOSS64 and then TERMINATE terminal application:
```
c:\netfoss\netfos64 /c1 /n1
@Echo off

C:\TER500\TERMINAT %1 %2 %3 %4 %5 %6 %7 %8
```

No issues here, so far. How to reproduce?

**Comment by leecher1337** [comment]
Sorry, I didn'r check with testbed

**Comment by pcmicro** [comment]
That solved it for Windows XP x64. Thanks again!
