### ISSUE TITLE
Can't find path for 16-bit application when double-clicked

### ISSUE THREAD

**Issue by lexterror** [leecher1337/ntvdmx64#19]
Everytime I try to run any 16-bit application it says it can't find the path...

"Windows cannot find 'C:\dic\Setup.exe' make sure you typed the name correctly, and then try again"

**Comment by leecher1337** [comment]
Is this a DOS executabe or Win16? WOW16 is not supported currently, as this deeply interacts with the Windows kernel and it is doubtful if it is even possible to get it running

**Comment by leecher1337** [comment]
closed as there was no further response
