### ISSUE TITLE
Run from Explorer.exe

### ISSUE THREAD

**Issue by peter8777555** [leecher1337/ntvdmx64#192]
I can run DOS programs from CMD console and it works well.

When i double clicks DOS programs from Explorer.exe(Windows 7 X64)

Show error message 

The version of this file is incompatible with the version of Windows you are running. 
Please check your computer's system information to determine if you need an x86 (32-bit) or x64 (64-bit) version of the program, 
and then contact the software publisher.

Can i run DOS programs from Explorer.exe ?

**Comment by leecher1337** [comment]
Maybe AppInitDLL key is missing or ther e is another reason why ldntvdm.dll isn't injected in either 32bit or 64bit explorer.exe or there is a problem patching explorer.exe.
As always, use DebugView to check if there is an execution error when loading the DOS application (in case ldntvdm.dll is injected into explorer.exe correctly), or if ldntvdm.dll isn't present in explorer.exe at all. To check presence of ldntvdm.dll in target Process, Process Explorer can show you the loaded modules of a process.

**Comment by peter8777555** [comment]
>To check presence of ldntvdm.dll in target Process, Process Explorer can show you the loaded modules of a process.

Yes,you are right.
I kill Explorer.exe and restart Explorer.exe 
It works well from Explorer.exe

Thamk you.
