### ISSUE TITLE
"Error while setting up environment"

### ISSUE THREAD

**Issue by lexterror** [leecher1337/ntvdmx64#20]
I'm unable to launch ntvdm.exe.

16-bit MS-DOS Subsystem
Command Prompt - ntvdm.exe
Error while setting up environment for the applicaton.

OS Version	10.0.14393.0 (Win10 RS1)

**Comment by leecher1337** [comment]
Please see #17 
New loader code now also outputs some information in DbgView console for analysis.
It seems that 32bit ldntvdm.dll (SysWOW64) loader is not properly installed, please verify with Process explorer.

**Comment by leecher1337** [comment]
No feedback for over 1 year, assuming fixed
