### ISSUE TITLE
32-bit processes crashing at startup (Windows 7)

### ISSUE THREAD

**Issue by throwaway768485** [leecher1337/ntvdmx64#202]
Lately I have had some 32-bit processes crashing at startup using `ldntvdm.dll` on Windows 7 x64.

The issue seems to lie in `Hook_Inline_Func` (detour.c, line 205) while patching a function in `kernel32.dll` (namely `BasepProcessInvalidImage`) :

`VirtualProtectEx(hProcess, (PBYTE)src - len, len + 2, PAGE_READWRITE, &OldProt))`

It turns out that the functions `VirtualProtectEx` and `BasepProcessInvalidImage` have their code located in the same memory page in the latest builds of `kernel32.dll`; thus the second call to `VirtualProtectEx` meant to restore the initial page protection triggers an exception, trying to execute no-more-executable code.

Replacing `PAGE_READWRITE` with `PAGE_EXECUTE_READWRITE` solved the issue for me.

Many thanks for your work on this great project!

**Comment by leecher1337** [comment]
Thank you for reporting, analysis and fix proposal saving me the hassle of needing to reproduce it!
