### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by dduttonnc** [leecher1337/ntvdmx64#205]
When running install bat, the installer is missing ansi.sys from the dos folder. 

D:\ntvdmx64-20220424\ntvdmpatch\release\dos\ansi.sys
This file can not be located anywhere

missing: D:\ntvdmx64-20220424\ntvdmpatch\release\ldntvdm\syswow64\ldntvdm.dll  
It's missing in the 11.0 folder, and I have to point it to 10.0

**Comment by leecher1337** [comment]
Check buildchk.log in w\minnt\base why ansi.sys hasn't been compiled or binplaced on your machine. The file is present, as long as you don't press a key after building completed and before it would clean up the build directory, so when being asked to press a key, simply check the logs in the directory.

Regarding ldntvdm.dll for win11, it's clearly there:
https://github.com/leecher1337/ntvdmx64/tree/master/ntvdmpatch/release/ldntvdm/syswow64/11.0

So I guess you can blame it on some crappy Antivirus sh*t on your system that deleted it. It is recommended to turn off Antivirus to prevent deletion of loader.

**Comment by areasudon** [comment]
The file is also missing on Github

**Comment by leecher1337** [comment]
> The file is also missing on Github
What do you mean by that? The file is meant to be built by the build script

**Comment by leecher1337** [comment]
Assuming invalid, closing
