### ISSUE TITLE
Autobuild created "W:" Drive

### ISSUE THREAD

**Issue by that1cutie** [leecher1337/ntvdmx64#207]
Using the NTVDMx64 autobuild, a new drive was created in My Computer which is labelled "W:" and contains "ntosbe-master" within it. After using autobuild, my DOS programs work fine again, but now I wish to hide the extra drive (or remove whatever is causing it while retaining DOS compatibility). Thank you!

**Comment by leecher1337** [comment]
If you do not want subst drive, refer to docs:

https://github.com/leecher1337/ntvdmx64/blob/9874abaf1fd2e373dc8afc5de766e577787faf09/ntvdmpatch/doc/autobuild.txt#L42

To remove (temporary) virtual drive at runtime:
```
subst w: /d
```
It would also be gone after reboot anyway.

**Comment by that1cutie** [comment]
Didn't realise reboot cleared it. Thank you!
