### ISSUE TITLE
Suggest to support Atlas OS

### ISSUE THREAD

**Issue by peter8777555** [leecher1337/ntvdmx64#209]
Atlas OS base on Windows 10.

https://atlasos.net/
https://atlasos.net/downloads

**Comment by leecher1337** [comment]
Looks liek a stripped down version of Windows 10, so one would think that it will work fine. What are the issues with it? Loader?

**Comment by peter8777555** [comment]
---------------------------------------------
Installing, please wait...
---------------------------------------------
Please check for completion-message from installer in taskbar.
[*] Preparing correct loader
