### ISSUE TITLE
Error download file ntvdmx64 when run autobuilt

### ISSUE THREAD

**Issue by triduong94** [leecher1337/ntvdmx64#213]
![1](https://user-images.githubusercontent.com/122363492/211991991-f515209d-d0a5-439a-a8af-8b418e453576.jpg)

**Comment by leecher1337** [comment]
https://github.com/leecher1337/ntvdmx64/blob/e0edd2c6791da15c08200956826ba8819b0c4a03/ntvdmpatch/doc/autobuild.txt#L59

Are you missing dwnl.exe in your build directory?
