### ISSUE TITLE
can't install on windows 11 -- your OS version is case-insensitive

### ISSUE THREAD

**Issue by urrickhunt** [leecher1337/ntvdmx64#215]
![install error](https://user-images.githubusercontent.com/96319944/215355587-64d4df95-5a5d-4702-a269-731bebe1c39a.png)

latest version all compiled flawlessly (both haxm & ccpu) however i was unable to install any of them on windows 11 enterprise.
is there a way around this? many thanks in advance this is an awesome project :)

**Comment by leecher1337** [comment]
Aha, interesting, so the version string of Windows 11 Enterprise is somehow different than with other Windows versions, I guess?
Can you please open a command shell (cmd.exe) and enter the command

```
ver
```

And paste the output here? Then I can check on how to parse the Windows version number from that one. Thanks.

**Comment by urrickhunt** [comment]
![ver](https://user-images.githubusercontent.com/96319944/215544816-1f19e858-0807-4e50-a7d3-c1cf6b535d08.png)

Microsoft Windows [Version 10.0.22000.1516]

**Comment by leecher1337** [comment]
Hm, String looks fine to me. Can you try to put `@echo on` to first line of install.bat and add a `pause` command at location where it is done parsing version in order to check what is causing this weird "case-insensitive" string?
