### ISSUE TITLE
Chrome not allowing download. Says the zip file is dangerous.

### ISSUE THREAD

**Issue by grey580** [leecher1337/ntvdmx64#216]
Chrome is detecting this as a virus.
![image](https://user-images.githubusercontent.com/12612300/216107555-e26459b2-641c-4bcf-abbc-e2cd95ee3be6.png)

Also Sophos is saying that the file is a virus and is cleaning it automatically. Might want to check it.

**Comment by leecher1337** [comment]
Duplicate

https://github.com/leecher1337/ntvdmx64/issues/10#issuecomment-1066044862
https://support.home.sophos.com/hc/en-us/articles/360041664851-How-to-submit-samples-of-suspicious-files-false-positives-to-Sophos

**Comment by grey580** [comment]
It's not just sophos that's flagging the file as malicious. Chrome is as well.

**Comment by grey580** [comment]
Windows defender also says that it's malicious
