### ISSUE TITLE
ESET Endpoint antivirus detects it on windows 11

### ISSUE THREAD

**Issue by haka-s** [leecher1337/ntvdmx64#224]
as the title says when i try to run it on windows 11 i get pop up saying it has deleted a file in memory, i don't get any indication as to wich file it is, i've whitelisted the files that get added to windows defender but i still get the detections, can you point me on wich file i should whitelist to stop getting these errors?

**Comment by leecher1337** [comment]
%systemroot%\syswow64\ldntvdm.dll
%systemroot%\system32\ldntvdm.dll

**Comment by haka-s** [comment]
i got them whitelisted already but i'm still getting the detections, i think it has something to do with the way it injects into the console process

**Comment by leecher1337** [comment]
Maybe ask your antivirus vendor on how to stop behavioural detection in the product or disable/uninstall it completely, there is not much that can be done from my side as I cannot influence the behaviour of the AV product.
