### ISSUE TITLE
Controlling cycles

### ISSUE THREAD

**Issue by donno2048** [leecher1337/ntvdmx64#228]
I have a DOS program that runs too fast on modern computers, on DOSBOX I just set the cycles to make it slower, is there a way to do so in ntvdmx64?

**Comment by leecher1337** [comment]
Not natively, but iirc, people always used [http://www.hpaa.com/moslo/](moslo) on NTVDM or plain DOS for such problems.
A downloadable copy of it can i.e. be found [https://www.suekayton.com/software/Moslo/Moslo.htm](here).
(not tested, though)

**Comment by donno2048** [comment]
That seems like an over-complication for me... I'll just stick to `cycles 5` on DOSBox, thanks though
