### ISSUE TITLE
NTVDM for 32 bit

### ISSUE THREAD

**Issue by Houfino** [leecher1337/ntvdmx64#231]
Hi people...Where can I download NTVDM for 32 bit? I only have 64x..I have Windows 10 32bit because of a weaker PC...Thanks...

Or both works 32/64?

**Comment by leecher1337** [comment]
`DISM /online /enable-feature /all /featurename:NTVDM`

https://learn.microsoft.com/en-us/windows/compatibility/ntvdm-and-16-bit-app-support

**Comment by Houfino** [comment]
> Thank you..It works!!!! :-)

I ask..How do I extract "Setup offline NTVDM" from Windows 10 32bit? I need to hide..I'm afraid that in the future Microsoft may remove :-/

**Comment by leecher1337** [comment]
I don't think that it will be removed from existing 32bit Windows versions, that wouldn't make sense.
They just don't release new 32bit Windows versions anymore, so it is being killed that way instead.

If you are afraid, you can download a Win10 32bit ISO and store it somewhere safe:
i.e.: https://www.techworm.net/2022/08/download-windows-10-iso.html

**Comment by Houfino** [comment]
> I don't think that it will be removed from existing 32bit Windows versions, that wouldn't make sense. They just don't release new 32bit Windows versions anymore, so it is being killed that way instead.
> 
> If you are afraid, you can download a Win10 32bit ISO and store it somewhere safe: i.e.: https://www.techworm.net/2022/08/download-windows-10-iso.html

Thank you...I see...I just wanted to extract only NTVDM 32x from Windows 10 32bit (ISO for example)...Too bad...

**Comment by leecher1337** [comment]
I don't see the point in just extracting the NTVDM-files, as NTVDM *cannot* work standanlone, it relies on a lot of supoprt functions in KERNEL32.DLL, NTDLL.DLL, CONHOSTV1.DLL (the console host subsystem), the kernel Console driver, etc. and even the kernel NTOSKRNL.EXE itself (on x32 for the V86 Monitor part).
If one part of the ecosystem breaks down, NTVDM won't be able to do anything, that's why you need to save the whole OS (i.e. the win 10 ISO).

**Comment by Houfino** [comment]
> I don't see the point in just extracting the NTVDM-files, as NTVDM _cannot_ work standanlone, it relies on a lot of supoprt functions in KERNEL32.DLL, NTDLL.DLL, CONHOSTV1.DLL (the console host subsystem), the kernel Console driver, etc. and even the kernel NTOSKRNL.EXE itself (on x32 for the V86 Monitor part). If one part of the ecosystem breaks down, NTVDM won't be able to do anything, that's why you need to save the whole OS (i.e. the win 10 ISO).

Thank you for the explanation :-)
