### ISSUE TITLE
NT BE path not found

### ISSUE THREAD

**Issue by DestoryG** [leecher1337/ntvdmx64#237]
it just report this error when i try to build it with minint

**Comment by leecher1337** [comment]
Then minnt cannot be found in the expected path within the directory structure.
Verify your build directory structure. Did you use autobuild?

**Comment by DestoryG** [comment]
no,this my directory:
![image](https://github.com/leecher1337/ntvdmx64/assets/136814177/008523dc-e457-4159-91ee-0735e505ea35)
![image](https://github.com/leecher1337/ntvdmx64/assets/136814177/dae31a62-f863-411d-9ea6-fc7479d49051)
![image](https://github.com/leecher1337/ntvdmx64/assets/136814177/49753e10-d626-491f-8605-4ffb33816525)
![image](https://github.com/leecher1337/ntvdmx64/assets/136814177/48ea7caa-f01f-4b52-902c-2c9abe10d101)

**Comment by leecher1337** [comment]
You made a typo, minint != minnt

**Comment by DestoryG** [comment]
You Are Right,Sorry :(

**Comment by DestoryG** [comment]
![image](https://github.com/leecher1337/ntvdmx64/assets/136814177/f091e9ba-8076-4b1d-b264-cc61f9a2bc39)
a new error?
