### ISSUE TITLE
NOT WORKING UNDER REMOTE DESKTOP

### ISSUE THREAD

**Issue by win64xx** [leecher1337/ntvdmx64#242]
When I try to use it under Remote Desktop (WINDOWS SERVER 2016) I get the message
that NTVDM.EXE stop working.

It works perfectly if I use it locally.

Thank you for your attention

Regards
Ernesto

**Comment by leecher1337** [comment]
Just tried it with Server 2022, my test application worked fine. Is it tied to a specific DOS-application, so does it also occur if you are just running command.com ?
Do you have a crash dump/stack trace of the crash?
https://learn.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

**Comment by leecher1337** [comment]
To be sure, I also tested it with Windows Server 2016, running DOS applications via Remote Desktop works the same as locally.

**Comment by leecher1337** [comment]
No more answer received within 1 year, closed
