### ISSUE TITLE
Autobuild doesn't work

### ISSUE THREAD

**Issue by jadenquinn** [leecher1337/ntvdmx64#251]
Here's what I get:
C:\Users\Jaden\Downloads\autobuild(1)>autobuild-all.cmd
----------------------------------------------------
Autobuild NTVDMx64
----------------------------------------------------

\w was unexpected at this time.

C:\Users\Jaden\Downloads\autobuild(1)>autobuild-all.cmd
----------------------------------------------------
Autobuild NTVDMx64
----------------------------------------------------

\w was unexpected at this time.

C:\Users\Jaden\Downloads\autobuild(1)>

I have no idea how do any building, I just want to use NTVDM, and the download I got from another site suddenly just doesn't install all the way and is now unusable.

**Comment by leecher1337** [comment]
Remove "(1)" from directory name, brackets are problematic, so i.e. rename directory to "autobuild"
