### ISSUE TITLE
Windows 11 update KB5035942 breaks ntvdmx64 (WIN10 KB50335491 may as well?)

### ISSUE THREAD

**Issue by kllkradio** [leecher1337/ntvdmx64#252]
Last night, I installed the 2024-03 Cumulative Update Preview for Windows 11 on my laptop.  After the update completed, ntvdmx64 was no longer recognized by the operating system and gave an error message that 16-bit programs are not supported.  I tried removing and reinstalling ntvdmx64 and got the same result.  There was also an error message as ntvdmx64 was attempting to be installed.  I suspect that this issue may also occur when KB50335491 is installed on a x64 Windows 10 computer.

I am using a build that I compiled last October which should be pretty up to date.

I was able to restore ntvdmx64 operation by uninstalling KB50335942.

Brian

**Comment by leecher1337** [comment]
Hi, I didn't find mentioned KB number, I only found KB5035942 , do you mean this one?
Normally, if updates are out that update a lot of system files, it may take a few days until the symbols are reade on the Microsoft Symbol Server. Until then, the loader cannot resolve the required symbols and will not work properly.
Did you check debugview output referring to some symbol resolution errors, maybe?
This usually is the most common cause for Windows updates breaking the loader.

**Comment by kllkradio** [comment]
Yes, KB50335942.  It was released yesterday.

Ahhh.  So maybe that is the problem. I didn’t have a chance to explore things further.

**Comment by kllkradio** [comment]
I reinstalled the update this evening and everything is now working fine.

Brian
