### ISSUE TITLE
NTVDMx64 stops working after I reinstalled it. 

### ISSUE THREAD

**Issue by happymimimix** [leecher1337/ntvdmx64#257]
![image](https://github.com/leecher1337/ntvdmx64/assets/107282563/f5c3f3cd-fce4-45dd-9963-0184782eebfc)
After uninstalling and reinstalling a newer version of NTVDMx64 it no-longer works for me. 

OS: Windows 10 22H2
Before: OCT 2023
After MAR 2024

Maybe a problem with file association? I guess?

**Comment by leecher1337** [comment]
Tested on Windows 10 x64 22H2 Build 19045.4291, works for me. Please check DbgView output if there are problems with the loader.

**Comment by sudo-000** [comment]
> See FAQ:
> 
> https://github.com/leecher1337/ntvdmx64/blob/b38510e28df77f0c3b5a6302f209b10e5ff027aa/readme.txt#L284
> 
> To be short: Yes, it gives OTVDM precedence over its own WOW16, when OTVDM is installed.

I'll try again later to install OTVDM first and then install NTVDM x64. 
Hope that would probably work. 
And also I'll look into the logs like you mentioned if that didn't work. 

I'm at school right now and don't have access to my pc to test this. I'll do that this evening.

**Comment by leecher1337** [comment]
No more update received on this, assuming solved.
