### ISSUE TITLE
Drive

### ISSUE THREAD

**Issue by WindowsNinetyTen** [leecher1337/ntvdmx64#258]
Can NTVDMx64 be installed from the D:\ drive and it would still copy the necessary files to C:\? Or should install.bat be run from the C:\ drive?

**Comment by leecher1337** [comment]
Installer location doesn't matter a lot. Just ensure that the pathname where the installer is placed isn't too long and doesn't contain spaces. So, i.e. running installer from d:\ntvdmx64 should work without issues, as everything is copied to the Windows directory.
