### ISSUE TITLE
SoundFX doesn't work.

### ISSUE THREAD

**Issue by WindowsNinetyTen** [leecher1337/ntvdmx64#261]
Even after I try the notime.reg file, I still get a message about limited time. Also, I get pop-ups from Norton about blocking activity from NTVDM.exe every time I open a program with SoundFX, and then the program closes.

**Comment by leecher1337** [comment]
Any reason why you want to use it? The important parts of SoundFX have already been incorporated into NTVDMx64, so I don't think that you'll get a lot of benefits by using it.

**Comment by WindowsNinetyTen** [comment]
I thought that I could improve the sound emulation. For example, on a game called Peach's Dream, the sound doesn't play properly, with glitchy sounds instead of the intended sound effects. Granted the official NTVDM is like this, but I thought that I could try to fix it. Also, I thought that I'd get good SoundBlaster Pro playback.

**Comment by leecher1337** [comment]
As we already had this in 2019, did you use the version I compiled for you? It shouldn't have any nags:
https://github.com/leecher1337/ntvdmx64/issues/40

**Comment by leecher1337** [comment]
No answer received in 6 months, assuming solved.
