### ISSUE TITLE
Does not install properly on Windows 11 IoT Enterprise LTSC Version 24H2 26100.712

### ISSUE THREAD

**Issue by mikedebian** [leecher1337/ntvdmx64#262]
Protection is off before compiling. All files compiled and are accounted for as far as I can tell. Installs, asks to reboot computer.
It worked fine on Windows 10 IoT LTSC.

Expected result : Run Win16 and DOS applications.
Result: This app can not run on this PC/Errors about PC being x64.

Shows up as installed under add remove programs.
Ran autobuild-ccpu-fre.cmd

**Comment by leecher1337** [comment]
Check debugview output if loader initializes and injects correctly into every process and past log here.

**Comment by mikedebian** [comment]
Debugview, can't get it to log or intercept anything in Windows 11 IoT Enterprise LTSC 24H2

**Comment by leecher1337** [comment]
Check, if ldntvdm.dll gets injected into every process, i.e. using Process Monitor. 
If not, check presence of ldntvdm im `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\AppCertDlls` registry key and that ldntvdm.dll is present in system32 and syswow64 directory.
At least it worked on 21H2. If Microsoft ruined something in 24H2, you may be out of luck.

**Comment by mikedebian** [comment]
I am so sorry, I had an application (windhawk) which injected itself in to the DLL's. I should have had it as the prime suspect.

**Comment by leecher1337** [comment]
Hopefully, you were able to solve it by removing windhawk. Closing. Feel free to open it, if problem persists.
