### ISSUE TITLE
The .pif has no icons! 

### ISSUE THREAD

**Issue by happymimimix** [leecher1337/ntvdmx64#265]
![image](https://github.com/leecher1337/ntvdmx64/assets/107282563/3ab3bd75-67df-4ef4-8ead-d050de6474a1)

Please fix this. @leecher1337

**Comment by happymimimix** [comment]
I'll have a try with this new version later, I'll let you know if the problem persists.

**Comment by leecher1337** [comment]
Any update on this topic, can issue be closed?

**Comment by happymimimix** [comment]
![image](https://github.com/user-attachments/assets/46479838-0b9e-4b86-af47-7e90260d5d26)
Yes, it worked. Thank you.
