### ISSUE TITLE
Problem with ldntvdm loader that interferes with WSL on Windows 11

### ISSUE THREAD

**Issue by leecher1337** [leecher1337/ntvdmx64#268]
Found this:

https://www.toughdev.com/content/2023/11/troubleshooting-hard-to-find-windows-subsystem-for-linux-wsl-crash-due-to-issues-with-ntvdmx64/

**Comment by leecher1337** [comment]
Problem can be fixed by creating
C:\windows\ldntvdm.ini with content:

```
[blacklist]
SearchIndexer.exe
wslservice.exe
```

Maybe ship this blacklist with default installation?

**Comment by mdanh2002** [comment]
Thank you for the fix. NTVDMx64 now works fine with both WSL and Windows Search.  I have also updated my blog article with this fix. Thank you once again.

**Comment by ringtailedfox** [comment]
does this work for Windows 10 users as well, or Windows 11 only?

**Comment by leecher1337** [comment]
Changelog states Win 10 and 11, so it should work on Win 10 too.
