### ISSUE TITLE
Correct the installation instructions in readme.txt

### ISSUE THREAD

**Issue by Korb** [leecher1337/ntvdmx64#269]
Currently, readme.txt contains the following text:

> **How to install**
> Now you can install the NTVDM on the destination machine:
> Run install.bat so that all files will be installed on the target machine

However, the downloaded autobuild.zip archive contains only the following files:

1. autobuild-all.cmd
2. autobuild-all-chk.cmd
3. autobuild-all-fre.cmd
4. autobuild-ccpu-chk.cmd
5. autobuild-ccpu-fre.cmd
6. autobuild-haxm-chk.cmd
7. autobuild-haxm-fre.cmd
8. dwnl.exe

and the install.bat file is missing.

**Comment by leecher1337** [comment]
The instructions are correct. One has to distinguish between BUILDING the product and INSTALLING to procut which are 2 completely different things.

The most important information is the *very first* 2 sentences of the readme:
https://github.com/leecher1337/ntvdmx64/blob/b5ebb0e2bc171d17265bd77708c3726928f5f014/readme.txt#L2

There is a whole section about compiling in the readme-file too.
If people are unable to read the readme-file from beginning to end, it is doubtful if they will be able to use the product correctly.
