### ISSUE TITLE
InstallSeild On win11

### ISSUE THREAD

**Issue by GiladDaKing** [leecher1337/ntvdmx64#278]
i tried to install the original commandos on my pc with ntvdmx64 but it didnt work i did it in a win 10 VM and it worked but in a win 11 VM it didnt do anything. the installer is called installsheild engine EXE
![image](https://github.com/user-attachments/assets/0584eaf3-d424-4850-8036-680f9da60328)

**Comment by leecher1337** [comment]
May be a bug in Windows 11, Installshield installers normally should be wrapped by Windows, maybe Installshield support broke in Win 11?
You can also see that InstallShield Engine EXE is a 32bit Process, so this is not a 16bit process and therefore not NTVDM related.
Contact Microsoft Support.

**Comment by leecher1337** [comment]
Additional note: As desribed in https://github.com/leecher1337/ntvdmx64/issues/227 Microsoft removed crucial functions for WOW16 16bit Windows Application support in Windows 11 22H2.
So NTVDM's support for 16bit Windows Applications is no more and never ever will come back as long as Microsoft doesn't restore the crucial functions that they removed, it's simply impossible from the technical point of view, as the whole WOW16 layer depends on these functions.
You best bet may be to install WineVDM (OTVDM). I don't think that it's related to your problem, as the installer executable is 32bit, but it doesn't hurt, in case you want to try it. 
It may still be benificial, as installing WineVDM prevents NTVDM from loading when executing a Win16 application (in case the setup launcher is 16bit) and maybe this results in Windows handing off Installshield to the appropriate handler function.

**Comment by GiladDaKing** [comment]
i didnt say that. but in the win 10 vm it opened an app called wowexec. i found it in the syswow64 folder and in win 10 it opened normally but in win 11 it didnt do anything. so i think that the problem because it looks like the installer is trying to open the wowexec

**Comment by leecher1337** [comment]
So maybe 32bit installer tries to run 16bit stub, but is unable to execute 16bit installer.
What you can try is to temporarily disable the ldntvdm-loader (see https://github.com/leecher1337/ntvdmx64/issues/277 ) and check if the installer starts without NTVDM (and also uninstall otvdm), as Windows has some compatibility mechanisms built in for old installers that may not get executed if 16bit-support is present.
If it really depends on WOWEXEC / WOW16 layer, you are out of luck, Microsoft simply completely ruined it in 22H2, you only can downgrade to Win 10 or rollback to a Win 11 release before 22H2 or run a VM with the application in that case, unfortunately.

**Comment by GiladDaKing** [comment]
it didnt work
![image](https://github.com/user-attachments/assets/c19cc6ca-bf34-45dc-9e4a-9036e765719c)
):

**Comment by leecher1337** [comment]
Ok, then you are out of luck with this installer and Win 11 version, unfortunately
