### ISSUE TITLE
[QUESTION] OTVDM and NTVDMx64 on the same machine

### ISSUE THREAD

**Issue by Lucas-mother3** [leecher1337/ntvdmx64#279]
Hello! I would like to know if it is possible to have both WineVDM (OTVDM) and NTVDMx64 on the same machine. Thanks in response.

**Comment by leecher1337** [comment]
Yes, it's possible, even recommended:

https://github.com/leecher1337/ntvdmx64/blob/7290f9095fd72b867e7579f44df785dd40a72666/readme.txt#L284
