### ISSUE TITLE
closed on start

### ISSUE THREAD

**Issue by GiladDaKing** [leecher1337/ntvdmx64#283]
after i installed ntvdmx64 and opened a 16bit app it just closed in a second

**Comment by leecher1337** [comment]
Win16 bit app or DOS app? Which OS version? Debugview Logs? Which application? Did you reboot after installation?
If console app, open in a console and check output.
Check eventlog application log for access violation or crash of ntvdm.exe, does it crash?
Evil Antivirus Software may also close down applications, if they don't like them.

Install ccpu checked version and tell it to enter yoda on ntvdm start (see readme), open vdmdebug and let it enter yoda, does it close before it has a chance to enter YODA? If in yoda, can you step through?
You can attach a debugger like x64dbg, if it sits in yoda, then continue in yoda, to check where ntvdm process terminates.

**Comment by GiladDaKing** [comment]
and i compiled it in win10 vm

**Comment by GiladDaKing** [comment]
also in the split second it wrote cant execute "the program that i was running"

**Comment by GiladDaKing** [comment]
it didnt work because the game was on my hard drive D: (also my i couldent cd to my drive from cmd) so it is not ntvdm problem

**Comment by GiladDaKing** [comment]
and if you know how to fix this problem can type it?
