### ISSUE TITLE
Ravioli Memory source code and blog post(s)

### ISSUE THREAD

**Issue by Amaroq-Clearwater** [leecher1337/ntvdmx64#31]
Here's a link to the source code for Ravioli Memory, and a link to the series of blog posts explaining what it is. Could _possibly_ come in handy for future development, assuming that you are willing to convert between conventional C and C++. All credit to both the concept and the code goes to Reengine, not myself.
https://github.com/reenigne/reenigne/tree/master/ravioli
https://www.reenigne.org/blog/rethinking-memory/

**Comment by leecher1337** [comment]
I don't see any memory fragmentation issues in NTVDM... We are working with memory pages (VirtualAlloc etc.) and memory management is done by the DOS Application within the bounds of allocated virtual memory, so what's the point of using ravioli here? I don't see the context...

**Comment by Amaroq-Clearwater** [comment]
I had mentioned it on another thread and you wanted me to provide more information and/or source code, so I did. No real reason besides that.

Though you probably wouldn't have much use for it, I do think there is a chance that it might eventually come in handy. Might not need it yet, but good to have just in case.
