### ISSUE TITLE
ldntvdm.dll does not inject in 64-bit apps since Dec22 update

### ISSUE THREAD

**Issue by Occupied** [leecher1337/ntvdmx64#32]
Hi, with the latest as of writing released ldntvdm.dll it fails to get injected via AppInit_DLLs for 64-bit processes, however it does get injected for 32-bit processes.
Replacing the ldntvdm.dll file with the previous one from commit ac93217 released Dec3 in System32 makes it work again.
Tested this on Windows 7 SP1 x64 and Windows 8.1 x64

**Comment by revelator** [comment]
Same here, im afraid :/

**Comment by leecher1337** [comment]
Confirmed on Windows 7, sorry for the inconvenience, investigating...

**Comment by Amaroq-Clearwater** [comment]
December 22? That means it got broken on my birthday >.<

**Comment by Occupied** [comment]
I have tested it on the Win8.1 machine, it works fine, thanks for the quick fix :)

**Comment by Occupied** [comment]
Now also tested on the Win7 x64 machine, works fine :)
About Win 8.0 x64, do you have any reports of it working?
For me it gets injected but as soon as I try to launch a DOS app it crashes...

**Comment by leecher1337** [comment]
Someone here in the bugtracker reported that it worked. I now improved the loader once more to circumvent osme potential crashes if DLL gets injected too early, can you please try and report back? 
Thank you.

**Comment by Occupied** [comment]
Thanks, I tried it but it still fails.
I read ticket #23 but I only actually see references to Win 8.1 in it?
Anyway, I will make a clean install of Win 8.0 later today to make sure it's not something messed up on that system.
If I can reproduce it I'll open a new ticket, so we don't take this one too off-topic :)

**Comment by leecher1337** [comment]
Hm, right, 8.1... I must admit I currently only tested it in windows 7 and Windows 10, as these are the most popular OS nowadays. Please just use DbgView by sysinternals and watch output of the loader, the loader talks a lot, if it gets loaded, so we may find out what the issue is.. Let's see if I got a Windows 8.0 VM somewhere...
