### ISSUE TITLE
ntvdmx64 need to be reinstall after windows update.

### ISSUE THREAD

**Issue by ohharsad** [leecher1337/ntvdmx64#34]
Is it normal to reinstall the ntvdmx64 after a windows update.

My server always need to reinstall ntvdmx64 after restart and update.

If restart without update, reinstall not needed.

**Comment by leecher1337** [comment]
Is suspect that it cleans out AppInit DLLs on update. Additionally, Windows Defender falsely detects the ldntvdm.dll loader as a virus, which may also lead to this undesirable result.
You can check if after the update if just the AppInit-DLL entries are missing in the registry.
You could make a logon script that puts the registry entries back in place (and copies missing files, if they get deleted too).
I also found AppInit DLL entries vanishing on Windows Server for some reason, maybe it's an obscure "security" feature from Microsoft...?
