### ISSUE TITLE
Three test files can NOT work

### ISSUE THREAD

**Issue by peter8777555** [leecher1337/ntvdmx64#35]
Three test files can NOT work

1.Run Clock.com
2.It can NOT run any DOS program again.

1.Run NP.EXE
2.It can NOT run any DOS program again.

1.Run PcManGame.exe and very SLOW speed.

**Comment by leecher1337** [comment]
1. Clock works as expected
I can run PcManGame fine on the same shell, for instance, so not reproducable for me, are you using the most recent release?  (see https://github.com/leecher1337/ntvdmx64/issues/7):

![grafik](https://user-images.githubusercontent.com/6495842/60807640-7e68d580-a186-11e9-87e7-7f207d62e864.png)

2. What is this program supposed to do? also after running it, I can launch another DOS application without a problem on the same shell.

3. Yes, console graphics and VGA emulation is very slow currently. I'm currently trying to rewrite the slow CVIDC-Interface in proper code, it may be benificial for Video performance, but there are thousands of lines of code, not sure if it will get us more performance, but it's worth a try.

**Comment by leecher1337** [comment]
https://github.com/leecher1337/ntvdmx64/commit/45d030dc798bd7906cee847a7e32f1f6538d535d improves performance of PcManGame a bit until CVIDC is being rewritten.

**Comment by peter8777555** [comment]
>are you using the most recent release? (see #7):

Yes.
I use OLD version ?

Update (6 January 2019)
ntvdmx64.7z 
SHA1:04a5393611f3a6918bf96dc153b7791b77dd68d0

I am not programmer.
Has the compiled version been updated since then?

Thank you a lot.

**Comment by peter8777555** [comment]
>console graphics and VGA emulation is very slow currently.
>improves performance of PcManGame a bit until CVIDC is being rewritten.

Good news.

Thank you a lot.

**Comment by leecher1337** [comment]
If you experience issues with execution NTVDM,ensure that ldntvdm.dll loaders are up to date (check file date of https://github.com/leecher1337/ntvdmx64/tree/master/ntvdmpatch/release/ldntvdm loaders, if they match yours. )

**Comment by peter8777555** [comment]
The web link show the files for  "5 months ago."
Those files are OLD.

**Comment by leecher1337** [comment]
https://github.com/leecher1337/ntvdmx64/issues/7
Just reinstall most current release,if in doubt

**Comment by peter8777555** [comment]
I have updated new version and everything is OK.
