### ISSUE TITLE
Need help building

### ISSUE THREAD

**Issue by Evernow** [leecher1337/ntvdmx64#36]
Hello there! Can I please have help building https://github.com/leecher1337/ntvdmx64? The patch.cmd keeps coming up with "patch.exe: file not found"... or something like that.
Any help is greatly appreciated!

**Comment by leecher1337** [comment]
Check that ntvdmpatch/util directory contains patch.exe, maybe it got deleted on download of repository somehow...?

Also check https://github.com/leecher1337/ntvdmx64/issues/7 if you don't get it to work

**Comment by peter8777555** [comment]
Does patch.exe patch which files ??

**Comment by leecher1337** [comment]
patch.exe patches all the files that are mentioned in the files in patches subdirectory

**Comment by leecher1337** [comment]
There now is a new build environment available to try
