### ISSUE TITLE
Support which VGA cards

### ISSUE THREAD

**Issue by peter8777555** [leecher1337/ntvdmx64#41]
I have a DOS program.

Error message :
Not support this VGA Card.

Support 
WD 90C3x,Cirrus GD542x,Trident,Tseng,S3,AHEAD V5000B ,
OAK,REALTEK,ALI,ATI,ARK,UMC VGA Card

***** support those VGA listed below *****
 WD      : 90C30, 90C31, 90C33
 Cirrus  : 5422, 5424, 5426, 5428
 Trident : 8800, 8900, 9000, TGUI94xx
 Tseng   : ET3000, ET4000, ET4000/W32x
 S3      : 86C911, 86C924, 86C801, 86C805, 86C928
 AHEAD   : V5000B
 OAK     : OTI-067, 077, 087
 REALTEK : RTG3105, 3106, 3108, 3109
 ALI     : ALG2201
 ATI     : MACH 32
 ARK     : ARK1000VL
 UMC     : UM85C408
 VESA    : VESA V1.x SPEC (BIOS or Driver)

Support VESA ?

**Comment by leecher1337** [comment]
Sorry, no VESA support yet. It wasn't available at the time when SoftPC was originally developed and therefore there is no emulation for it in the code.
32bit x86 Windows NTVDM doesn't even use VGA emulation but instead relies on fullscreen for graphic output, therefore it wasn't a problem there as VESA graphics was done by the real hardware.
Until Windows 8 came out and removed XPDDM display  driver model support, thus fullscreen wasn't available anymore and graphics support in NTVDM died with it. Btw.: Windows 7 32bit still supports XPDDM and therefore it can be tricked into supporting Fullscreen.

**Comment by peter8777555** [comment]
Thank you for detail info.

1.
What is the max XRes/YRes/Colors for NTVDMX64 ?

2.
Trident : 8800, 8900, 9000, TGUI94xx
Tseng : ET3000, ET4000, ET4000/W32x
S3 : 86C911, 86C924, 86C801, 86C805, 86C928

Support these VGA cards ?
