### ISSUE TITLE
Mouse support

### ISSUE THREAD

**Issue by peter8777555** [leecher1337/ntvdmx64#42]
NTVDMX64 seem have mouse support.

But some DOS programs  can NOT work.

Ex:
Norton Utility : NCD.exe
Norton DOS : NHelp.exe

**Comment by leecher1337** [comment]
That's correct, verified it with real 32bit NTVDM, also doesn't work there in windowed mode, only in fullscreen (where real hardware gets used)

**Comment by peter8777555** [comment]
I found a solution to work
.
Please refer to the Sample.zip for more details.

[Sample.zip](https://github.com/leecher1337/ntvdmx64/files/3390364/Sample.zip)
