### ISSUE TITLE
Show wrong text

### ISSUE THREAD

**Issue by peter8777555** [leecher1337/ntvdmx64#43]
I test two DOS programs and show wrong text.

Please view 
SnapShot01.png
SnapShot02.png
SnapShot03.png
SnapShot04.png

**Comment by leecher1337** [comment]
May be realted to Video card emulation. On real NTVDM x32,it only works in fullscreen (so real hardware), when you switch back to windowed, it also garbles screen there.
Just for fun,I tried it in vDOS/vDOSPlus and it doesn't seem to work there either.

**Comment by peter8777555** [comment]
The DOSBox works.

Website:
http://ykhwong.x-y.net/
File:
http://www.msu.edu/~yootaewo/_db/20150125.7z

The Test.zip is very very useful program for ALL Chinese guys.
I hope NTVDMX64 can work and thank you a lot.
