### ISSUE TITLE
Strange name

### ISSUE THREAD

**Issue by peter8777555** [leecher1337/ntvdmx64#44]
"mem /c" show strange name.

![z1](https://user-images.githubusercontent.com/29886853/61165710-6c0be480-a556-11e9-844a-772c45cfbbf7.png)

**Comment by leecher1337** [comment]
The mem command from the leaked NT4 source is too old to handle device drivers properly.
Just use mem.exe from original NT4, this one works.

**Comment by peter8777555** [comment]
Yes,you are right.

I try three mem.exe of WinNT4/Win2000/WinXP.
All of them works very well.

Thank you a lot.
