### ISSUE TITLE
About compile problem "Invalid argument"

### ISSUE THREAD

**Issue by peter8777555** [leecher1337/ntvdmx64#45]
I try to compile step by step.

W:\ntvdmpatch\updates\001-sb20
patch.cmd is OK.

But

W:\ntvdmpatch\updates\002-demlfn>patch.cmd
dos\dem\demlfn.c
dos\dem\demlfn.h
2 File(s) copied
patch: **** write error : Invalid argument

--------------------------------------------

W:\ntvdmpatch\updates\003-romemu>patch.cmd
patch: **** write error : Invalid argument

What is wrong ?

**Comment by leecher1337** [comment]
Try to add --verbose switch to patch.exe call in patch.cmd to see what's going on.
Maybe some of the files/folders that need to be patched are write protected?

**Comment by peter8777555** [comment]
W:\ntvdmpatch\updates\002-demlfn\patch.cmd
The patch.cmd open file "poa27264.txt" by Notepad.exe

W:\ntvdmpatch\updates\003-romemu\patch.cmd
The patch.cmd open file "poa27012" by Notepad.exe

![2](https://user-images.githubusercontent.com/29886853/61255433-1ffdb180-a79b-11e9-8571-4989b359ebfa.png)

![3](https://user-images.githubusercontent.com/29886853/61255437-23913880-a79b-11e9-9944-37f5b29c77e7.png)

![2a](https://user-images.githubusercontent.com/29886853/61255612-dc577780-a79b-11e9-9fa1-4d1d1b02c935.png)

![3a](https://user-images.githubusercontent.com/29886853/61255619-e11c2b80-a79b-11e9-95e8-1c997f529aa9.png)

**Comment by Houdhey** [comment]
I got a problem like this, I think I solved it by doing this : 
https://www.groovypost.com/howto/microsoft/remove-lock-icons-folders-windows-7/

**Comment by peter8777555** [comment]
The Windows XP have NO any lock symbols from folders.

I have trid to compile on three kinds of OS and login as Administrator account.
(Windows 7 X64 Chinese/Windows XP X86 Chinese/Windows XP X86 English).

I have trid to compile OVER 20-30 times but it FAILED again again.
I have no any ideas on this issue.

SHA1:

old-sdk.trunk_r57.20150728.7z 
eaa5734b6610059cdc37dd31f40634be763a9132

old-src.trunk.r687.20150728.7z
69e899b9aa17342f9982f70cea99edb195daf923

I bypass W:\NTVDMX64\MyBuild\ntvdmpatch\updates ALL patch.cmd

>bld-ntos.cmd
BUILD: Done
    121 files compiled - 28023 LPS
    7 libraries built - 2 Warnings
    10 executables built - 38 Warnings
Build error. Process aborted.

>bld.cmd
BUILD: Done
    496 files compiled - 2575 Warnings - 4 Errors - 14637 LPS   --> Erro Message
    29 libraries built - 2 Warnings - 1 Errors   --> Erro Message
    10 executables built - 354 Warnings - 40 Errors   --> Erro Message
Build error. Process aborted.

>mkrelease.bat
Cannot open file W:\binaries\nt\ntvdm.exe  --> No build ntvdm.exe

PS:
I have watch ALL youtube videos about how to build the NTVDNX64.

**Comment by peter8777555** [comment]
By the way,
When i Recompiled again,which ways are correct ?

A.
Remove W:\*.*
Unpack old-sdk.trunk_r57.20150728.z and old-src.trunk.r687.20150728.z 
patch -> zSHtst -> bld-ntos -> bld -> mkrelease

B.
patch -> zSHtst -> bld-ntos -> bld -> mkrelease

Now,i use A option.
