### ISSUE TITLE
ntvdmx64-master dos folder missing, you must set up the Razzle...

### ISSUE THREAD

**Issue by Houdhey** [leecher1337/ntvdmx64#47]
Hello,

Sorry for posting two issues in the same day, but it is a different one.
I'm still trying to install your program on a Windows Server 2012 R2.
I've downloaded the latest file in github, ntvdmx64-master.

I've run the patch first. It took 5 seconds. Then I ran the installation. I met a problem, looking for ANSI.SYS file.

![screen2](https://user-images.githubusercontent.com/44744194/61459224-8d147100-a96c-11e9-8111-ea8e07ea0821.jpg)

So what I did is that I've taken an ansi.sys file from an other installation i set in the past. The installation continued.
And then it tells me that it is looking for files in a dos folder, which does not exist in the ntvdm64-master.
Other thing : On the SysWow64 and System32, the ANSI.SYS files were missing. I don't know why. 

Can someone help me?

![screen3](https://user-images.githubusercontent.com/44744194/61459652-833f3d80-a96d-11e9-98a4-ece030e901f6.jpg)

**Comment by leecher1337** [comment]
Did you follow the compilation instructions (there is even a video demonstrating it)? 
Looks like you forget to run mkrelease, maybe?
Alternatively, see https://github.com/leecher1337/ntvdmx64/issues/7

**Comment by Houdhey** [comment]
I'm going to try again, indeed it did not run mkrelease. Actually, I jumped the Compilation Steps, because it ran without these steps on one of my computers. 
And these steps are non-understandable for me (I'm not an expert user, just a student)

_Prepare your machine according the the OpenNT project build instructions:
   a) Unpack contents of old-src directory from 
      old-src.trunk.r687.20150728.7z to your working directory
      You do not need to extract the .svn folder in it_

Where is the old-src.trunk.r687.20150728.7z file? And what is it? I would love some help about these compilation steps. If I success on the installation, I'll make a very guided tutorial to people like me (newbies).

**Comment by leecher1337** [comment]
Well, due to legal reasons I cannot release a fully working copy here on github, as this would violate copyright and I don't want this repository to be DMCAed as this would be the end of this project.
Fortunately, other people took the burden of compiling it for you ;-)

**Comment by Houdhey** [comment]
Ok I see. I tried to do it by myself. I successfully arrived until step **3a**. Actually, the video was unfortunately cut after step 3.

When I do **bld-ntos.cmd**  or **bld.cmd** , is that normal to have this?
![1](https://user-images.githubusercontent.com/44744194/61489822-d9cb6c80-a9ab-11e9-96df-b301500c0202.jpg)


And when I do **mkrelease.bat,** I have this error : "**The specified path does not exist"** (in french)
![dosmissing](https://user-images.githubusercontent.com/44744194/61489861-eea80000-a9ab-11e9-9851-91f2ef13a3b7.jpg)

**Once again, now I have my dos folder, but it is empty. W:\ntvdmpatch\release\dos**

**Comment by leecher1337** [comment]
There is a part 2 of the video where it continues.
Someone also made a nice tutorial in one video where the steps are shown:
https://www.youtube.com/watch?v=unU7uyFJWmo

**Comment by Houdhey** [comment]
Hello,

I met the same problem as here [#18](https://github.com/leecher1337/ntvdmx64/issues/18) and I did as you said 

> Copy alias.exe in tools(HOSTARCH)\idw directory to your local system32 directory.
> e.g. If your host machine is x86, copy tools\i386\idw\alias.exe to %SystemRoot%\system32

But it did not work and still display "You must set up the Razzle build environment..."

I tried this on a Windows 7 64 bit.
Where is the problem?

**Comment by leecher1337** [comment]
Building only works on Windows XP 32bit. I should have mentioned it in the Readme, but as I was originally referring to the OpenNT build instructions, I didn't mention it seperately. I will correct this missing information on the next update of the README file.

**Comment by Houdhey** [comment]
Okey, thanks for this information

**Comment by 0x6A7232** [comment]
Ah, can you put that notice in a more conspicuous location?  Like at the beginning of that section, or maybe a NB at the top?  It's kind of at the tail end of the src instructions right now.  And I gotta be honest, in a large document where you're already skimming for the steps to take, it's easy to miss.  But we have a compiled version available ( http://www.columbia.edu/~em36/ntvdmx64.html ) so it's not so bad.  And it's not that I don't have access to XP, I do, it's just that setting it up would be a PITA (up to a couple hours of work to get an XP VM to the point where I can do 10 minutes of work?  xP)

I really should get a few old OSes set up in permanent VMs that migrate with systems.  Sometime.
