### ISSUE TITLE
Issue with Visual Studio debugger

### ISSUE THREAD

**Issue by kuenzign** [leecher1337/ntvdmx64#5]
When I installed this on my Windows 10 machine, I wasn't able to run projects from Visual Studio (specifically 2012 and 2015).  I would attempt to run a program using the Visual Studio interface, but it would just hang and not be able to run.  On a potentially related note, the Slack desktop application would not launch as well.  Whenever I uninstalled ntvdmx64, the issues were fixed, but if I reinstalled it, the issues returned.  Any thoughts?

**Comment by leecher1337** [comment]
This might be related to the loader code (ldntvdm.dll) that needs to propagate between processes using some nifty tricks. It can be that there are issues with some types of applications that don't like the way the DLL gets injected into them.
I guess you are using the most recent .dlls from this repository where at least one IAT parsing bug got fixed...?
To diagnose the issue, you may want to attach x64dbg to the processes tht have a problem on startup and check if there is a crash on the ldntvdm-code.

**Comment by kuenzign** [comment]
I found that I was still able to launch the compiled project exe and then use Visual Studio to attach the debugger to the process, but it wouldn't work the normal way.

**Comment by leecher1337** [comment]
Just downloaded https://slack.com/downloads/instructions/windows on my Test-VM and launched it, worked normally here (Though I'm unable to find it once I close it, where the heck does it install to?)...

**Comment by leecher1337** [comment]
Can confirm the Visual Studio problem, I guess it has something to do with the loader launching the target application suspended, mabye debugger thread by debugger gets frozen too and never resumes, will investigate this.

**Comment by leecher1337** [comment]
This only affects console applications to be debugged, is this correct?
That would make sense as we only suspend target process on creation there, then inject our code and resume (which seems to fail somehow making it impossible to resume the target process). On processes that are using Windows subsystem, injection gets already done in a clean way by AppInit.

**Comment by leecher1337** [comment]
Fix released. Please check and confirm that it fixes the bug, then issue can be closed.

**Comment by leecher1337** [comment]
There hasn't been an answer to this issue for almost 30 days, assuming it is fixed and closing.
