### ISSUE TITLE
patching file gfx_updt.c

### ISSUE THREAD

**Issue by peter8777555** [leecher1337/ntvdmx64#51]
I compiled old version ntvdmpatch(4/26/2019) and finish to compile.

When i use new version ntvdmpatch(7/12/2019) but it can NOT finish to compile.

w:\ntvdmpatch\patch.cmd

patching file `private\mvdm\softpc.new\base\video\gfx_updt.c'
Hunk #5 succeeded at 3642 (offset -11 lines).

**Comment by leecher1337** [comment]
Thank you for your report, hopefully fixed now?

**Comment by peter8777555** [comment]
Great !! It works and finish to compile.

I bypass W:\ntvdmpatch\updates\ ALL patch.cmd

Can you review the issue ??

W:\ntvdmpatch\updates\001-sb20\patch.cmd
It is OK.

BUT,

W:\ntvdmpatch\updates\002-demlfn\patch.cmd

dos\dem\demlfn.c
dos\dem\demlfn.h
2 File(s) copied
patch: **** write error : Invalid argument

W:\ntvdmpatch\updates\003-romemu\patch.cmd

patch: **** write error : Invalid argument

The patch.cmd ALWAYS run notepad.exe 

---------------------------
Notepad
---------------------------
The filename, directory name, 
or volume label syntax is incorrect.
---------------------------
OK   
---------------------------
