### ISSUE TITLE
Suggestion batch files for backup/restore functions

### ISSUE THREAD

**Issue by peter8777555** [leecher1337/ntvdmx64#52]
I try and error over 30 times for building.

:Loop
Unpack Big files
Compile step 1 ...... step N
Remove ALL files
Goto Loop

Can you create a Backup/Restore.bat for backup/restore patching files  ONLY ?
I can save time and boring time.

Unpack Big files
:Loop
Backup.bat
Compile step 1 ...... step N
Restore.bat
Goto Loop

**Comment by leecher1337** [comment]
I suggest to use a version control system like SVN or GIT (why reinvent the wheel?).
Prepare your source-directory, check it in to your version control system server, apply patches,do a commit.
If patches get updates, do a revert to initial revision and reapply patchset, commit etc.

**Comment by peter8777555** [comment]
I have a idea.
I can use VMWare snapshot  function.
Windows XP +Source Code -> Take snapshot.
I unpack ntvdmx64-master.zip ONLY.

**Comment by leecher1337** [comment]
SVN revert would be faster than rolling back a whole VM,but of course, your idea would work too.
