### ISSUE TITLE
Recall Windows commands

### ISSUE THREAD

**Issue by peter8777555** [leecher1337/ntvdmx64#55]
I can use UP/Down key to recall Windows commands.
But
When i run ANY TSR programs,i can NOT use UP/Down key to recall Windows commands anymore.

**Comment by leecher1337** [comment]
Doskey was NEVER a part of command.com !

**Comment by peter8777555** [comment]
I view config.nt/autoexec.nt,no load DOSKEY.EXE at startup.

Microsoft NTVDM recall Windows commands function:

1. Internal function.
2.External function by call DOSKEY.EXE

Which one  ?

**Comment by leecher1337** [comment]
I'm not aware of any doskey implementation that is compatible with Windows NT command.com implementation, so I would consider it impossible. It was never supported.
doskey.exe from Windows is just for 32bit cmd.exe and therefore useless, doskey.com from MS-DOS also doesn't work with Windows NT's command.com

**Comment by leecher1337** [comment]
http://www.c-bit.org/Q/165214/EN-US/
"
The following functions do not work in Windows: ...
	Interrupt 2F dealing with the DOSKEY program call outs (AX = 4800) is not supported. "

**Comment by peter8777555** [comment]
It is a strange question.
If NTVDM do not use doskey.com(DOS) and doskey.exe(Windows).

1.I can use UP/Down key to recall Windows commands and run DOS programs.

2.When i run TSR program,the UP/Down key to recall Windows commands will FAILED forever.
Is this TSR program destory recall Windows commands function ?

**Comment by leecher1337** [comment]
As soon as you are in a session with a running DOS application in background (i.e. installed TSR), you are on command.com from now on, not on CMD.EXE

If you just run a DOS-application from CMD.EXE, you quit back to CMD.EXE
If you i.e. open a DOS shell from a DOS program or run a TSR in background, you quit back to DOS (and you need to be on DOS from now on so that TSR can run, so you are inside NTVDM) and so you are on COMMAND.COM
CMD.EXE is capable of doskey-functions, COMMAND.COM is not.
Clear now?

**Comment by peter8777555** [comment]
Yes,Clear,
I have try some tests and you are right.
Thank you very much for your detail info.

1. Run DOS programs --> In CMD.exe --> It can use UP/Down key.
2. Run TSR  program   --> In Command.com --> It can NOT use UP/Down key.
3. UnLoad TSR program --> In CMD.exe --> It can use UP/Down key.

1. Run DOS programs --> In CMD.exe --> It can use UP/Down key.
2. Run DOS shell from a DOS program   --> In Command.com --> It can NOT use UP/Down key.
3. Exit DOS Shell and DOS  program --> In CMD.exe --> It can use UP/Down key.
