### ISSUE TITLE
About cvidc-new/patch.cmd

### ISSUE THREAD

**Issue by peter8777555** [leecher1337/ntvdmx64#59]
Here is a short howto on how to compile for readme.txt
Can you upate a short howto for cvidc-new/patch.cmd ?
What is the compiled order for  step 3 and 3a and cvidc-new/patch.cmd ?

step 3 -> 3a -> cvidc-new/patch.cmd ?
step 3 -> cvidc-new/patch.cmd -> 3a ?
or other step ?

**Comment by leecher1337** [comment]
Shuold be applied after step 3, but I haven't tested it yet, so I cannot guarantee you that it runs through properly yet. Testing the patch is on my TODO list (that's why it isn't documented yet), but if you want to test it, feel free to try :-)

**Comment by peter8777555** [comment]
bld_Error.txt

    502 files compiled - 2652 Warnings - 2 Errors - 14283 LPS
    29 libraries built - 2 Warnings
    10 executables built - 354 Warnings - 40 Errors

[bld_Error.txt](https://github.com/leecher1337/ntvdmx64/files/3500096/bld_Error.txt)

**Comment by leecher1337** [comment]
New release should build cleanly and now incorporates CVIDC-NEW interface by default.

**Comment by peter8777555** [comment]
Good job and thank you.
