### ISSUE TITLE
ntvdmx64 and the upcoming build of Windows 10

### ISSUE THREAD

**Issue by AEAEAEAE4343** [leecher1337/ntvdmx64#60]
Currently have Windows 10 Insider Preview installed with ntvdmx64 and all is going well. Well, until I read on the Windows Insider blog that there were new "experimental features". This included more fonts, transparency etc. When trying these features out I quickly ran in to the typical message you would get trying to run 16 bit apps in 64 bit windows: "The program or feature cannot start or run due to incompatibility with 64-bit versions of Windows". After doing some research I found out that these feautures rely on a completely new console host. (Which will replace the old one in the upcoming semi-annual update but is still in the Insider builds as a backup) I'm basically here to inform you and ask if you know about any of this stuff

**Comment by leecher1337** [comment]
Oh crap... So basically this could mean the end of ntvdmx64 on newer Win10 releases then? :-(
Without a compatible conhost, we are screwed. Dod you ensure that the Regkey that enforces ConhostV1 is still present? We rely on ConhostV1 anyway, ConhostV2 was not and never will be compatible with NTVDMx64 as it is lacking console graphics features.

Maybe restoring old conhost.exe and associated DLLs from a previous Win10 release works...?
How do I get this experimental version? Switching Win10 to Insider preview and updating it to the latest release?

**Comment by AEAEAEAE4343** [comment]
At the moment it is still there, it’s just that I read that it will be removed when the new conhost is stable.

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: leecher1337 <notifications@github.com>
Verzonden: Wednesday, August 21, 2019 8:52:39 AM
Aan: leecher1337/ntvdmx64 <ntvdmx64@noreply.github.com>
CC: AEAEAEAE4343 <anis1errais@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [leecher1337/ntvdmx64] ntvdmx64 and the upcoming build of Windows 10 (#60)


Oh crap... So basically this could mean the end of ntvdmx64 on newer Win10 releases then? :-(
Without a compatible conhost, we are screwed. Dod you ensure that the Regkey that enforces ConhostV1 is still present? We rely on ConhostV1 anyway, ConhostV2 was not and never will be compatible with NTVDMx64 as it is lacking console graphics features.

Maybe restoring old conhost.exe and associated DLLs from a previous Win10 release works...?
How do I get this experimental version? Switching Win10 to Insider preview and updating it to the latest release?

**Comment by AEAEAEAE4343** [comment]
After doing some more research I found out that they aren't _removing_ the old one, they're just _disabling_ it. So I think the registry fix is enough. For now we can't look into the future so I'll close the thread until there's definitive news

**Comment by AEAEAEAE4343** [comment]
Hmm, after reinstalling ntvdmx64 it seems that it just works with conhost v2.

**Comment by leecher1337** [comment]
Tried VGA graphics too?

**Comment by AEAEAEAE4343** [comment]
That just crashes the console. But it at least tries to start it. Text-based stuff like command.com work though

**Comment by AEAEAEAE4343** [comment]
Oh and anything that tries to adjust terminal size crashed too (eg. edit.com)

**Comment by AEAEAEAE4343** [comment]
When running directly (not via a consolehost v2 cmd shell) it enforces V1 and works perfectly
