### ISSUE TITLE
"Razzle Build Environment"

### ISSUE THREAD

**Issue by ObsidianPlague** [leecher1337/ntvdmx64#66]
For every time I try to launch `bld-ntos` through `zSHtst `, it keeps saying the following:
`You must set up the Razzle build environment prior to executing this command.`
`Supported build configurations: *fre, *tst, *chk`

Is there any way to get this working?

**Comment by leecher1337** [comment]
Seems like the build environment doesn't get set up correctly for you. Did you ensure that you are running it under 32bit Windows XP?

**Comment by ObsidianPlague** [comment]
Yeah, it's running under XP 32bit.

**Comment by leecher1337** [comment]
echo %PROCESSOR_ARCHITECTURE% should result in x86, maybe this environment variable is not set on your Windows installation?
You can also check this video to compare your setup and see if there is something different on your machine: https://www.youtube.com/watch?v=unU7uyFJWmo

**Comment by leecher1337** [comment]
In case you are still having troubles: Does new MINNT build environment work for you?

**Comment by leecher1337** [comment]
No answer was received within approx 2 years, assuming you got familiar with MinNT build system in the meantime.
