### ISSUE TITLE
Could it resize command prompt window to fullscreen on Windows 10 x64? If it can't, things would crash.

### ISSUE THREAD

**Issue by FellFromTheSky** [leecher1337/ntvdmx64#68]
Some DOS programs need to be run at fullscreen (for example DOOMS19).
However the original NTVDM isn't able to resize it's window size to fullscreen in Windows 10.
So the DOS program would crash.
I think it's an issue with Windows 10 command prompt, because pressing Alt + Enter wouldn't resize it's window to fullscreen.

Is this bug already fixed in NTVDMx64?
Thanks.

**Comment by leecher1337** [comment]
Just for reference, inc case someone finds this closed ticket: https://github.com/leecher1337/ntvdmx64/issues/41#issuecomment-510906104

Short answer: Unfortunately, this is impossible to fix due to windows driver architectural changes.
