### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by MaxMiddendorp** [leecher1337/ntvdmx64#70]
How to uninstall this prduct?!

**Comment by leecher1337** [comment]
Like all other applications, Control panel/Software

**Comment by AwsomeDood20** [comment]
leecher, I cant uninstall this.

**Comment by tuffss** [comment]
How do I uninstall NT Vdm64

**Comment by leecher1337** [comment]
Are you blind?

https://github.com/leecher1337/ntvdmx64/issues/70#issuecomment-574153900

**Comment by samerkh** [comment]
what is the name that i should look for in control panel, because i dont seem to find it. While installing i got (not enough memory) error, and when i ran install again it says that ntvdm is installed and i should uninstall it from the control panel, but i cant find it there anyway.

**Comment by leecher1337** [comment]
Name is "NTVDM x64". If it isn't there, you can try:

```
RunDll32 advpack.dll,LaunchINFSection ntvdmx64.Inf,DefaultUninstall
```

in the directory hwere ntvdmx64.inf is located (If installation is successful, it is in Windows\inf directory, otherwise running it in the installer directory may also work.
If you want to skip the install-check of the installer for already instaled ntvdm, just delete Windows\syswow64\ntvdm.exe

**Comment by GGuyX** [comment]
> Name is "NTVDM x64". If it isn't there, you can try:
> 
> ```
> RunDll32 advpack.dll,LaunchINFSection ntvdmx64.Inf,DefaultUninstall
> ```
> 
> in the directory hwere ntvdmx64.inf is located (If installation is successful, it is in Windows\inf directory, otherwise running it in the installer directory may also work. If you want to skip the install-check of the installer for already instaled ntvdm, just delete Windows\syswow64\ntvdm.exe

Neither of the solutions work. This is dumb...

**Comment by GGuyX** [comment]
> Name is "NTVDM x64". If it isn't there, you can try:
> 
> ```
> RunDll32 advpack.dll,LaunchINFSection ntvdmx64.Inf,DefaultUninstall
> ```
> 
> in the directory hwere ntvdmx64.inf is located (If installation is successful, it is in Windows\inf directory, otherwise running it in the installer directory may also work. If you want to skip the install-check of the installer for already instaled ntvdm, just delete Windows\syswow64\ntvdm.exe

Neither of the solutions work - This is kinda dumb in all honesty.. Why not just provide, I dunno, an script to remove all files and everything else?

**Comment by leecher1337** [comment]
Because the .inf file IS the script that removes all the files?

**Comment by SoundCrafterYT** [comment]
I have the exact same problem. I still have some of it left on my PC after uninstallation through Control Panel. Where can I find the loader?

**Comment by leecher1337** [comment]
%systemroot%\system32
%systemroot%\syswow64

**Comment by SoundCrafterYT** [comment]
it's ldntvdm i suppose. because a 64bit program is crashing bc of that. Is it safe to delete?

**Comment by leecher1337** [comment]
Yes, ldntvdm.dll
Safe to delete. But when it's currently in use, you first have to rename it, because you won't be able to delete it. After renaming, you can reboot and then remove it.
Which program does it crash, are there any stacktraces of the crash?

**Comment by SoundCrafterYT** [comment]
Roblox Player. It just says:
```
Roblox Player has crashed because of an incompatible
software:
/Harddisk2/System32/ldntvdm.dll
```
