### ISSUE TITLE
NTVDMx64 Does not run

### ISSUE THREAD

**Issue by Sanches8002** [leecher1337/ntvdmx64#71]
I installed NTVDMx64 on my Windows 10 x64, but any program I start gives the error: This app can't run on your PC. I already tested it on a virtual machine and it works correctly. Does anyone know to explain to me what may be happening?

**Comment by peter8777555** [comment]
Try
https://www.tenforums.com/tutorials/94146-enable-disable-legacy-console-mode-all-consoles-windows-10-a.html

**Comment by leecher1337** [comment]
Sounds like the loader is not being injected correctly into all applications.
You can check the AppInit keys, if they are in place.
If so, check with Process Explorer if the ldntvdm.dll is being injected into applications.
Also Windows Defender Antivirus is known to falsely flag the loader as a virus and prevents it from running. So check Windows defender, if it maybe detected the loader as a virus and mark it as a permitted application. Window Defender also tends to remove the AppInit key, so it has to be readded and afterwards, a reboot may be required.
If the loader is being injected correctly into the applications, you can use Sysinternals DebugView to check the output of the loader on the debug console. For instance, if it cannot fetch the symbols for your versions of system DLLs from the Microsoft Symbol Server, it cannot patch correctly also resulting in a failure.

**Comment by leecher1337** [comment]
No update given on the ticket within 2 years, assuming ticket is resolved, closing.
