### ISSUE TITLE
CD Command fails when a DOS program shells to COMMAND.COM

### ISSUE THREAD

**Issue by pcmicro** [leecher1337/ntvdmx64#74]
Many DOS programs have an option to "Shell to DOS", or in the case of a BBS program it will allow users to shell to a door program from the main BBS.  However under NTVDMx64 (February 1 2020 build), the shelled to Command.com (or batch file running under it), fails to allow the CD command to change the directory. This behavior was observed using several different DOS BBS programs, either to shell to a door, or to shell to a COMMAND.COM prompt.

**Comment by leecher1337** [comment]
Please provide a demo application (when possible including source code) where the behaviour can be reproduced. Normal shell-out from DOS applications like i.e. MS WORKS 2.0 work flawlessly.

**Comment by pcmicro** [comment]
I have sent you an example.

**Comment by ddscentral** [comment]
Not sure if this is related, but I can't change the current directory in DOS applications directly either, for example the old Borland Pascal compiler.

**Comment by pcmicro** [comment]
I see the problem in both Turbo Pascal 7 (i.e. RemoteAccess), and Borland C++ 3.1 (i.e. ProBoard), so it could be specific to old Borland DOS compilers.

**Comment by ddscentral** [comment]
This isn't specific to Borland, "cd" doesn't work even when running command.com directly.

**Comment by peter8777555** [comment]
I use build on 2019Y/09M/16D.
No "CD" problem.

**Comment by pcmicro** [comment]
> This isn't specific to Borland, "cd" doesn't work even when running command.com directly.

I am able to open Command.com from the start menu, and use CD to change the directory without issue. I only see the issue with CD not working if I run a DOS program that allows me to shell to Command.com. I am using the pre-compiled version from the University of Columbia site, which has binaries dated February 1 2020, but I do not know which build this actually is.

**Comment by pcmicro** [comment]
Peter8777555: Could you contact me regarding the build you mentioned?  My address is mike@ <my username> .com

**Comment by peter8777555** [comment]
To:pcmicro

I use build on 2019Y/09M/16D.
No "CD" problem.

You need to build by youself.
ntvdmx64-master.zip

[ntvdmx64-master.zip](https://github.com/leecher1337/ntvdmx64/files/4238194/ntvdmx64-master.zip)

![z1](https://user-images.githubusercontent.com/29886853/75075424-bf0c3800-5538-11ea-9c83-90b4b7ffb569.gif)

![z2](https://user-images.githubusercontent.com/29886853/75075438-c59aaf80-5538-11ea-9e9b-44eacea5cce4.gif)

**Comment by pcmicro** [comment]
Thanks leecher1337 this bug is fixed so I will close this issue.
