### ISSUE TITLE
NTVDMx64 crashes after clicking twice with the mouse

### ISSUE THREAD

**Issue by MrPepka** [leecher1337/ntvdmx64#75]
The console works great until I run any DOS game. After clicking twice with the mouse on the window with this DOS game the console crashes. Some games have to be handled with the mouse, so I can't test some of them. What should I do? I attach crash dumps

[conhost.exe.9788.zip](https://github.com/leecher1337/ntvdmx64/files/4237180/conhost.exe.9788.zip)

**Comment by leecher1337** [comment]
Interesting, this looks like a bug in Microsoft Windows conhost, not NTVDMx64. Can you give me an executable (game) that I can use to try to reproduce the crashes?

**Comment by MrPepka** [comment]
The games I have seen in this are:
Leisure Suit Larry 3 and 5
Ramon's Spell
Trick or Treat
[Trick-or-Treat_DOS_EN.zip](https://github.com/leecher1337/ntvdmx64/files/4250321/Trick-or-Treat_DOS_EN.zip)
[Ramon's Spell_PL.zip](https://github.com/leecher1337/ntvdmx64/files/4250325/Ramon.s.Spell_PL.zip)
[Leisure_Suit_Larry_3.zip](https://github.com/leecher1337/ntvdmx64/files/4250328/Leisure_Suit_Larry_3.zip)
[leisure_suit_larry_5_-_a_little_undercover_work.zip](https://github.com/leecher1337/ntvdmx64/files/4250330/leisure_suit_larry_5_-_a_little_undercover_work.zip)

**Comment by leecher1337** [comment]
Hm, I cannot reproduce a crash with i.e. Trick or Treat. I guess you should just recompile NTVDMx64. As of today, I have a new convenient MINNT build system available so that you should be able to recompile it following the instructions. There also is a youtube video showing the process.

**Comment by MrPepka** [comment]
OK, should I delete the current NTVDMx64 or can I leave it? It may also be important that I have a Corsair NightSword RGB mouse with iCUE? Did other games work for you?

**Comment by leecher1337** [comment]
When changing to minnt repository, it may be better to uninstall old version via control panel first and then install new one, because the files are different and not compatible.

Generally, regarding support for games, protected mode games most likely don't work, but they often also had problems with classic NTVDM. For gaming, DOSbox may be a better solution, because NTVDM never was optimized for that.

**Comment by MrPepka** [comment]
Unfortunately, reinstalling the patch and recompiling it didn't help. Games for NTVDM start and even music is heard, but after double-clicking on the game window, the window closes, but the sound from the game continues and the ntvdm.exe process must be closed manually in the task manager

**Comment by leecher1337** [comment]
I think I was able to reproduce your crash. It only occurs if Quick Edit mode for the console is turned on.
If you turn it off, the crash doesn't happen. It seems that conhost forgets to check whether it is in graphics mode or not for QuickEdit handling.

**Comment by leecher1337** [comment]
I think I was able to reproduce your crash. It only occurs if Quick Edit mode for the console is turned on.
If you turn it off, the crash doesn't happen. It seems that conhost forgets to check whether it is in graphics mode or not for QuickEdit handling.

**Comment by MrPepka** [comment]
Thanks, it helped. Now the games are running as normal
