### ISSUE TITLE
Fail minnt repository build system

### ISSUE THREAD

**Issue by peter8777555** [leecher1337/ntvdmx64#76]
5) Run ntvdmpatch\minnt\mktools.cmd
   to prepare the build environment tools

-----------------------------------

== Initialising the sizzle environment for building NTOSBE tools ... ==
Repository Name        (NTREPO)        = NTOSBE
Source Path            (NTROOT)        = C:\work\NTOSBE-master\src
Target Architecture    (NTARCH)        = x86
Target Build           (NTBLD)         = chk
Target                 (NTTARGET)      = x86chk
NTOSBE Root            (BEROOT)        = C:\work\NTOSBE-master
NT Binary Tree         (NTTREE)        = C:\work\NTOSBE-master\src.bin\x86chk

== Building local tools ... ==

[mkmsg]
BUILD: Adding /Y to COPYCMD so xcopy ops won't hang.
BUILD: Using 4 child processes
BUILD: Object root set to: ==> objchk
BUILD: Beginning build phase: 0
BUILD: Object root set to: ==> obj0chk
BUILD: Compile and Link for X86
BUILD: Beginning build phase: 1
BUILD: Object root set to: ==> obj1chk
BUILD: Compile and Link for X86
BUILD: Beginning build phase: 2
BUILD: Object root set to: ==> obj2chk
BUILD: Compile and Link for X86
BUILD: Beginning default build phase
BUILD: Object root set to: ==> objchk
BUILD: Compile and Link for X86
BUILD: Computing Include file dependencies:
BUILD: Examining c:\work\ntosbe-master\src\sdktools\mkmsg directory for files to compile.
    c:\work\ntosbe-master\src\sdktools\mkmsg
    c:\work\ntosbe-master\src\sdktools\mkmsg - 2 source files (1,262 lines)
BUILD: Saving C:\work\NTOSBE-master\src\build.dat...
BUILD: Compiling c:\work\ntosbe-master\src\sdktools\mkmsg directory
1>c:\work\ntosbe-master\makefile.def(4033) : warning  U1088:
BUILD: NMAKE.EXE -c BUILDMSG=Stop. NTTEST= UMTEST= BUILD_PHASE= NOLINK=1 NOPASS0=1 X86=1 failed - rc = 2
BUILD: Linking c:\work\ntosbe-master\src\sdktools\mkmsg directory
1>c:\work\ntosbe-master\makefile.def(4033) : warning  U1088:
BUILD: NMAKE.EXE -c BUILDMSG=Stop. LINKONLY=1 NOPASS0=1 NTTEST= UMTEST= BUILD_PHASE= X86=1 failed - rc = 2
BUILD: Done

Failed to copy mkmsg to tools directory.

Error Build aborted.

**Comment by leecher1337** [comment]
Weird, doesn't occur on my machine. Try the following:
edit ntosbe-master\buildlocaltools.cmd and change

`build -c`
to
`build -c -e`

Then try to run mktools.cmd agin and check ntosbe-master\src\sdktools\mkmsg\buildchk.log
Maybe you find out which tool in the build chain is causing the error. Maybe rc.exe?

**Comment by peter8777555** [comment]
ntosbe-master\src\sdktools\mkmsg\buildchk.log

BUILD: Compile and Link for X86
BUILD: Compile and Link for X86
BUILD: Compile and Link for X86
BUILD: Compile and Link for X86
BUILD: Computing Include file dependencies:
BUILD: Examining c:\work\ntosbe-master\src\sdktools\mkmsg directory for files to compile.
Compiling c:\work\ntosbe-master\src\sdktools\mkmsg directory ********************
'NMAKE.EXE -c BUILDMSG=Stop. NTTEST= UMTEST= BUILD_PHASE= NOLINK=1 NOPASS0=1 X86=1'
1>BUILDMSG: Processing c:\work\ntosbe-master\src\sdktools\mkmsg
1>WARNING:  missing nmake.err; displaying error numbers without messages.

1>C:\work\NTOSBE-master\makefile.def(4033) :  U1088: 

1>Stop.

BUILD: NMAKE.EXE -c BUILDMSG=Stop. NTTEST= UMTEST= BUILD_PHASE= NOLINK=1 NOPASS0=1 X86=1 failed - rc = 2
Linking c:\work\ntosbe-master\src\sdktools\mkmsg directory ********************
'NMAKE.EXE -c BUILDMSG=Stop. LINKONLY=1 NOPASS0=1 NTTEST= UMTEST= BUILD_PHASE= X86=1'
1>WARNING:  missing nmake.err; displaying error numbers without messages.

1>C:\work\NTOSBE-master\makefile.def(4033) :  U1088: 

1>Stop.

BUILD: NMAKE.EXE -c BUILDMSG=Stop. LINKONLY=1 NOPASS0=1 NTTEST= UMTEST= BUILD_PHASE= X86=1 failed - rc = 2

**Comment by leecher1337** [comment]
Maybe the makefile.def of your copy of the NTOSBE build environment got damaged somehow? 
In my copy, it's exactly 133911 bytes.
@stephanosio Do you have an idea why this is happening?

**Comment by leecher1337** [comment]
Can you check your PATH environment variable? Maybe you have another version of nmake in your system path that gets precedence over NTOSBE nmake and spits out the error?
Easy check: If you just open a commnd prompt and typ nmake, is there some nmake available?

**Comment by peter8777555** [comment]
I find the question.
My Path include K:\DOS
K:\DOS has many tools NMAKE.exe LINK.exe ....
So mktools.cmd get WRONG NAME.exe LINK.exe 
I set Path EMPTY and work.

**Comment by peter8777555** [comment]
Yes. You are right.

Now

[rcdll]
"C:\work\NTOSBE-master\src\sdktools\rcdll"
BUILD: Adding /Y to COPYCMD so xcopy ops won't hang.
BUILD: Using 4 child processes
BUILD: Object root set to: ==> objchk
BUILD: Beginning build phase: 0
BUILD: Object root set to: ==> obj0chk
BUILD: Compile and Link for X86
BUILD: Beginning build phase: 1
BUILD: Object root set to: ==> obj1chk
BUILD: Compile and Link for X86
BUILD: Beginning build phase: 2
BUILD: Object root set to: ==> obj2chk
BUILD: Compile and Link for X86
BUILD: Beginning default build phase
BUILD: Object root set to: ==> objchk
BUILD: Compile and Link for X86
BUILD: Loading C:\work\NTOSBE-master\src\build.dat...
BUILD: Computing Include file dependencies:
BUILD: Examining c:\work\ntosbe-master\src\sdktools\rcdll directory for files to compile.
    c:\work\ntosbe-master\src\sdktools\rcdll
    c:\work\ntosbe-master\src\sdktools\rcdll - 1 Pass Zero files (1,793 lines)
BUILD: Building generated files in c:\work\ntosbe-master\src\sdktools\rcdll directory
1>Compiling message file - rcmsgs.mc for all platforms
1>rcmsgs.mc(43) : error : Unterminated message definition
1>NMAKE :  U1077: 'mc' : return code '0x1'
BUILD: NMAKE.EXE -c BUILDMSG=Stop. NTTEST= UMTEST= NOLINK=1 PASS0ONLY=1 BUILD_PHASE= X86=1 failed - rc = 2
BUILD: Examining c:\work\ntosbe-master\src\sdktools\rcdll directory for files to compile. (2nd Pass)
    c:\work\ntosbe-master\src\sdktools\rcdll
    c:\work\ntosbe-master\src\sdktools\rcdll - 31 source files (18,137 lines)
BUILD: Compiling c:\work\ntosbe-master\src\sdktools\rcdll directory
1>Precompiling - rc.h for X86
1>Compiling - rcdll.rc for X86
1>rcdll.rc(9) : error RC2135 : file not found: MSG00001.bin
1>NMAKE :  U1077: 'rc' : return code '0x1'
BUILD: NMAKE.EXE -c BUILDMSG=Stop. NTTEST= UMTEST= BUILD_PHASE= NOLINK=1 NOPASS0=1 X86=1 failed - rc = 2
BUILD: Compile errors: not linking c:\work\ntosbe-master\src\sdktools\rcdll directory
BUILD: Done

    3 files compiled - 4 Errors -   816 LPS
Build command failed for rcdll.

Error Build aborted.

**Comment by leecher1337** [comment]
Maybe some message compiler (mc.exe) still in your PATH that doesn't like Japanese characters?

You can test with:
c:\work\ntobe-master\tools\x86\mstools\mc.exe c:\work\ntobe-master\src\sdktools\rcdll\rcmsgs.mc

For me, it generates message files correctly. If it doesn't for you or complain, maybe .mc file is damaged in your copy, otherwise maybe a broken/old mc has precedence.

**Comment by peter8777555** [comment]
I have remove our PATH and use Windows 7 X64 OS  default path.

C:\>c:\work\ntosbe-master\tools\x86\mstools\mc.exe c:\work\ntosbe-master\src\sdktools\rcdll\rcmsgs.mc
MC: Compiling c:\work\ntosbe-master\src\sdktools\rcdll\rcmsgs.mc
c:\work\ntosbe-master\src\sdktools\rcdll\rcmsgs.mc(43) : error : Unterminated message definition

**Comment by peter8777555** [comment]
I re-download NTOSBE-master.zip 

I got the same error.

**Comment by leecher1337** [comment]
So either mc.exe or rcmsgs.mc maybe got devastated.
As mc.exe gets built during mktools process, maybe the locally compiled version is flawed?
To check this, please restore mc.exe from NTOSBE original repository and check with that copy again 

https://github.com/stephanosio/NTOSBE/raw/master/tools/x86/mstools/rc.exe
https://github.com/stephanosio/NTOSBE/raw/master/src/sdktools/rcdll/rcmsgs.mc

Or try mc on a fresh NTOSBE repository without running mktools.cmd before.

As a sidenote, rebuilding the local utilities via mktools is not absolutely necessary, it may also work with the tool versions supplied with NTOSBE, however, these lead to some random problems sometimes, that's why I recommended building the utilities locally in the build instructions.

**Comment by peter8777555** [comment]
I compare with HASH.
Both of them is the same as NTOSBE-master.zip

**Comment by leecher1337** [comment]
So if
tools\x86\mstools\mc.exe src\sdktools\rcdll\rcmsgs.mc

fails on a new, fresh checked-out NTOSBE, maybe the problem is related to your operating system version or locale? As it doesn't happen on my systems, I can only make wild guesses about the nature of the problem. Do you have a VM to compare? iirc you have a Windows XP VM for your old-src builds, maybe you can try if it fails in there too?

**Comment by peter8777555** [comment]
I see your YouTube video,you use Windows 10 to build.

Now,
I try again and use Windows XP in VMWare.
I got the same error.

So,
Real PC : Windows 7 X64
VMWare: : Windows XP X86.

I got the same error.

**Comment by peter8777555** [comment]
By the way,

minnt.txt
old-src.trunk.r687.20150728.7z or old-src-sr687.7z

You use old-src-sr687.7z
I use old-src.trunk.r687.20150728.7z 

Does this the question ?

**Comment by peter8777555** [comment]
>1>rcmsgs.mc(43) : error : Unterminated message definition

I think is file question.
So i try to convert end of line 0xA to 0xD 0xA
It works.

**Comment by leecher1337** [comment]
Interesting... I have file with just 0A line endinges in it and mc.exe still works fine.
Basically I just 

wget https://github.com/stephanosio/NTOSBE/raw/master/tools/x86/mstools/mc.exe
wget https://github.com/stephanosio/NTOSBE/raw/master/src/sdktools/rcdll/rcmsgs.mc
mc rcmsgs.mc

and it works here. I wonder why your target machines are picky about it... But anyway, 0D 0A line endings are a good idea on Windows systems.

**Comment by peter8777555** [comment]
C:\>c:\work\ntosbe-master\tools\x86\mstools\mc.exe c:\work\ntosbe-master\src\sdktools\rcdll\rcmsgs.mc
MC: Compiling c:\work\ntosbe-master\src\sdktools\rcdll\rcmsgs.mc
c:\work\ntosbe-master\src\sdktools\rcdll\rcmsgs.mc(43) : error : Unterminated message definition

C:\>c:\work\ntosbe-master\tools\x86\mstools\mc.exe c:\work\ntosbe-master\src\sdktools\rcdll\rcmsgs.mc
MC: Compiling c:\work\ntosbe-master\src\sdktools\rcdll\rcmsgs.mc

**Comment by stephanosio** [comment]
Make sure that the `autocrlf` setting is properly configured when using Git on Windows.

```
git config --global core.autocrlf true
```

**Comment by peter8777555** [comment]
6) Run NTOSBE-master\sizzle_minnt.cmd

I do NOT have sizzle_minnt.cmd
I have sizzle.cmd ONLY.

**Comment by peter8777555** [comment]
>and it works here. I wonder why your target machines are picky about it...
> But anyway, 0D 0A line endings are a good idea on Windows systems.

You use Windows 10.

I know,Notepad.exe support Unix file form Windows 10.
Maybe this is the reason.

Chinese Web :
https://kknews.cc/zh-tw/tech/lerrrrz.html

**Comment by leecher1337** [comment]
Maybe you refreshed NTOSBE in between.. 
The sizzle_minnt.cmd will be placed by the patch.cmd process of ntvdmpatch\minnt\patch.cmd process.

**Comment by peter8777555** [comment]
i find C:\work\ntvdmpatch\minnt\minntfix\NTOSBE-master\sizzle_minnt.cmd
Can i use ?

**Comment by leecher1337** [comment]
You must ensure that ntvdmpatch\minnt\patch.cmd runs through properly before compiling buildtools, otherwise patches won't get applied to NTOSBE and you may get nasty suprises. 
When sizzle_minnt.cmd is not present, this is asign that the patch.cmd hasn't been completed yet.

Maybe you'd better start over again now that you know the problems and can fix them before?

**Comment by peter8777555** [comment]
Windows 7 X64 Build finish.

1.
 I get 3 versions Only ?
C:\work\ntvdmpatch\releases
br
CHS
CHT

2.
When run mktools.cmd
.......
press ANY key 
run again
........
press ANY key 
close CMD Console.

**Comment by peter8777555** [comment]
I test MinNT Version.
But i do NOT like this version.

My CMD console in code page 950.

Old NTVDMX64 version:
My old DOS exe can use code page 950.

MinNT Version:
It ALWAYS use code page 437.
Oh my god,that is bad news for me.

**Comment by leecher1337** [comment]
That's interesting, I wonder why all languages get built for me.. Actualle we are using the same sourcecode...?

Regarding the codepage problem: Is there a way I can reproduce this on my system?
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/chcp
I don't see that 950 is a valid setting there. Also, chcp is a WIN32 program that gets executed to show the console settings.
When I
`chcp 850`    (valid codepage for my system and default here)
and then run
`command.com`
and then enter `chcp`, cp850 is being kept.
For verification, I think from what I can see, @emendelson updated his builds already in #7 
Maybe you can try his builds and see if you get the same problems with the builds from there (you can test USA build and the build for your system language to check if there are differences).
So we can check if this is a general problem with Minnt version or if it is related to the build process.

**Comment by peter8777555** [comment]
I test "emendelson build".
It still ALWAYS use code page 437.

I test "command.com".
It still ALWAYS use code page 437.

I test "HelloPas.exe".
It still ALWAYS use code page 437.

[HELLOPAS.zip](https://github.com/leecher1337/ntvdmx64/files/4254745/HELLOPAS.zip)

![1](https://user-images.githubusercontent.com/29886853/75333001-4bfc1c00-58c0-11ea-92f0-2cb04255d2e9.gif)

![2](https://user-images.githubusercontent.com/29886853/75333014-51596680-58c0-11ea-9aa9-20af3b10c284.gif)

**Comment by peter8777555** [comment]
I test "emendelson USA build".
It Works.

It is a strange question.

**Comment by leecher1337** [comment]
Maybe this is related to the special contry.sys that gets copied on CHS, CHT, ... builds (see minnt\base\mvdm\bin86\cht\ directory)?
As I don't have any Taiwanese or Chinese Windows version available, I cannot test this myself :(
Can you try to use the CHT build with the USA build country.sys just for testing?

**Comment by peter8777555** [comment]
I try build again on Windows XP VMWare.

![X2_patch cmd](https://user-images.githubusercontent.com/29886853/75354737-74980c00-58e8-11ea-80ee-f997ad9fb160.png)

![X3_mktools cmd](https://user-images.githubusercontent.com/29886853/75354787-8083ce00-58e8-11ea-96bc-3bc8596e1810.png)

![X6_bld-minnt cmd_1](https://user-images.githubusercontent.com/29886853/75354797-8679af00-58e8-11ea-9c80-14d4c5d141c2.png)

![X6_bld-minnt cmd_2](https://user-images.githubusercontent.com/29886853/75354822-8da0bd00-58e8-11ea-92bc-00c2a4d42312.png)

![X7_mkrelease-minnt](https://user-images.githubusercontent.com/29886853/75354832-91ccda80-58e8-11ea-832c-176356bfae82.png)

**Comment by leecher1337** [comment]
I had this weird keypress issue once, too. But if you press a key, it will actually NOT run again but continue with building the tools. 
Haven't found out, why it makes this "pause" call in the middle of the process and pretends that it has finished when it has not. But I only had this issue once.

**Comment by peter8777555** [comment]
So i should Close consle OR keypress to run again ?

**Comment by peter8777555** [comment]
My Real PC with path k:\dos
Suggestion:
Do NOT run NMAKE/LINK/..... from PATH var.

**Comment by leecher1337** [comment]
> So i should Close consle OR keypress to run again ?
Press a key and wait until it closes on its own.

**Comment by peter8777555** [comment]
>Can you try to use the CHT build with the USA build country.sys just for testing?

 I have test and NOT works.

**Comment by peter8777555** [comment]
I guess can NOT build due to with 0xA line end.

Maybe you try to build in Windows XP VM.

**Comment by peter8777555** [comment]
>Alternatively, you can try to invoke
>buildlocaltoolsshell.cmd x86
>and then on this shell
>cd src
>build
>That should also compile the toolchain

4>Linking Executable - sdktools\touch\objchk\x86\touch.exe for X86
3>Linking Executable - sdktools\m4\objchk\x86\m4.exe for X86
1>Linking Executable - sdktools\hsplit\objchk\x86\hsplit.exe for X86
2>Linking Executable - sdktools\hextract\objchk\x86\hextract.exe for X86
3>Linking Executable - sdktools\wcshdr\objchk\x86\wcshdr.exe for X86
BUILD: Done

    510 files compiled - 9 Errors - 19552 LPS
    25 libraries built
    32 executables built
    31 files binplaced

C:\work\NTOSBE-master\src>

**Comment by leecher1337** [comment]
I think we have triggered some really weird batch file processing bug here.
In buildlocaltools.cmd, if I take the block

`call :Build touch sdktools\touch bldtools\touch.exe idw\touch.exe`
`if errorlevel 1 goto Error`

and add
`REM  xxxxx xx xxxxxxxxxx`

underneath it, it doesn't build at all. I get an endless loop with Building and cleaning up then.
Seems like the program counter of the batch file processor gets corrupted somehow simply be using this batch file...

**Comment by leecher1337** [comment]
Tried compiling on my Windows XP machine, with the latest 2 commits, build process went through smoothly. All languages were built.

**Comment by leecher1337** [comment]
> > Can you try to use the CHT build with the USA build country.sys just for testing?
> 
> I have test and NOT works.

I checked with Taiwanese Windows 2000, it seems that it behaves exactly the way that you described. So I guess, you have to stick with USA version:

![Windows 2000 Taiwan-2020-02-26-18-41-11](https://user-images.githubusercontent.com/6495842/75371823-c2504c80-58c7-11ea-90db-5152d6d1b4e9.png)

![Windows 2000 Taiwan-2020-02-26-18-41-49](https://user-images.githubusercontent.com/6495842/75371829-c67c6a00-58c7-11ea-8520-f7e094fd1ad4.png)

![Windows 2000 Taiwan-2020-02-26-18-53-02](https://user-images.githubusercontent.com/6495842/75372618-17d92900-58c9-11ea-9e1e-db6eb323f7e6.png)

**Comment by peter8777555** [comment]
>I checked with Taiwanese Windows 2000, it seems that it behaves exactly the way that you described. 
>So I guess, you have to stick with USA version:

Thank you.

**Comment by peter8777555** [comment]
>Tried compiling on my Windows XP machine, with the latest 2 commits, 
>build process went through smoothly. All languages were built.

I try on Windows 7 X64,it still FAILED.

I will try Windows XP VMWARE.

My Files with MD5 HASH

MD5 Hash

ntvdmx64-master.zip
b65940c2e7390bbcb1ac7a99317937f6

MinNT-20170416-85fac4faadc77203db8ddc66af280a75c1b717b0.zip
f65cde4720e2bc064e90273f7bebbf3e

NTOSBE-master.zip
c4d2ad492b7eea2e27088f6d64e7b8e7

GRMSDK_EN_DVD.iso
a7a4aa8a9f5b648f5771eafe2286817f

GRMWDK_EN_7600_1.iso
8fe981a1706d43ad34bda496e6558f94

old-src.trunk.r687.20150728.7z
cc1ae95ec17e1beadcc363282ea8e725

**Comment by leecher1337** [comment]
If you still have this masm386 error, maybe you can check in minnt\base\buildchk.log which file it fails to compile.
Maybe there are CRLF issues on other files that only appear on your Windows Version or something like that...? I suspect so, because 0A line endings didn't hurt my mc.exe, but they definitely hurt your mc.exe, so maybe it has to do with the language version of the Windows machine used for compiling...?

**Comment by peter8777555** [comment]
Does MinNT-20170416-85fac4faadc77203db8ddc66af280a75c1b717b0.zip need to rename q160765803-minint4-85fac4faadc7.zip ?

**Comment by leecher1337** [comment]
No, filename of minnt repository zip doesn't matter, because you need to unpack its contents to work directory anyway, so it's not used or touched by preparation/patch script.
I hope the buildchk.log will shed some light on the build problems.

**Comment by peter8777555** [comment]
I will try Windows XP VMWARE,it still FAILED.

Yes,i guess is correct.
Many many Error:Unexpected end of line

I use Windows XP/7 CHT edtion.

[ErrorWinXP.zip](https://github.com/leecher1337/ntvdmx64/files/4257680/ErrorWinXP.zip)

**Comment by peter8777555** [comment]
Oh,my god.

Do i need to try in English edtion ?

**Comment by leecher1337** [comment]
The .zip file you can download from github seems to keep 0A line endings. stephanos above posted a setting how to fetch package with converted line endings via git, maybe that's the simplest solution to get a working repository?

**Comment by peter8777555** [comment]
stephanosio > git config --global core.autocrlf true

How to ?

I do NOT know.

git is EXE ?

**Comment by peter8777555** [comment]
By the way,
You can build in Windows XP/10.
This project  can NOT build in Two-Bytes Windows OS ? 
Ex: CHT/CHS/JPN/KOR Edtion.

**Comment by peter8777555** [comment]
I find MANY .gitignore  files.

I need add one line "git config --global core.autocrlf true" to ALL .gitignore  ?

**Comment by leecher1337** [comment]
I'm not really familiar with git, but I think this is just a command to execute:

`git config --global core.autocrlf true`

and then the git.exe client sets this in its global config file and you can checkout the repository with this setting.

The reason for the CRLF problem on your windows version is just a guess, I haven't tried it with far east Windows versions myself yet.

**Comment by peter8777555** [comment]
I'm not really familiar with git,too.

Maybe i try build in English edtion more EASY.

I will try later.

**Comment by leecher1337** [comment]
What is interesting is that the errors you encounter are actually found in generated files that the buildmsg tool creates. 
Now I have this code in my patch.cmd file that should fix line endings for .msg files, which get converted to the mentioned files that throw the error:

```
echo Ensuring that msg files have CRLF
pushd %BASEPATH%\mvdm\dos\v86\messages
for /R %%f in (*.msg) do (
  more /p <%%f >tmp.msg
  %PATCHROOT%\util\sed -i "s/^        /\t/g" tmp.msg
  move tmp.msg %%f
)
```

So I'm using more /p and then rename the file back to do the conversion.
Can you please check, if the .msg files in mvdm\dos\v86\messages directory have CR LF line endings? If not, maybe the "more /p" stuff doesn't work on your system as expected.

**Comment by peter8777555** [comment]
Here you are for files.

[command.zip](https://github.com/leecher1337/ntvdmx64/files/4258068/command.zip)

[messages.zip](https://github.com/leecher1337/ntvdmx64/files/4258069/messages.zip)

**Comment by peter8777555** [comment]
My PC has used over 10 years,so it is slow speed.

Windows 7 X64 is my Host OS,if it can build is more better.
Windows XP is VMWare OS,it is very SLOW speed to build. :-(((((((

I hope Windows 7 X64 can build,the speed is better.

**Comment by leecher1337** [comment]
Ok, this isn't a CRLF-issue from git, it really has to do with your locale. The buildmsg tool converts various characters that are unknown to him to ? on your system, whereas on my system, they get piped through. Will have to investigate this further. Might also be interesting for stephanos.

**Comment by peter8777555** [comment]
Thank you.

I back to old version 2019Y/09M/16D.

Waitting for new version.

By the way,
Windows 10  get piped through ?
Windows XP can NOT ?

**Comment by leecher1337** [comment]
buildmsg is actually a msdos utility that gets compiled and the converted using msdos player (because it has to run somehow without NTVDM being available on a potential build system).
Now I suspect that msdos player has an incompatibility with your system charset and therefore incorrectly does some sort of character transformation and this in turn produces faulty output. So I may need to write a buildmsg version that is 32bit capable.

**Comment by peter8777555** [comment]
So,if i try build in English edtion,it will PASS to  build ?

**Comment by peter8777555** [comment]
By the way,
The build to create multi-language versions,it seem by English order.

I got 3 versions.
br cht chs then failed cs  .....

Suggestion:
USA version first then by English order.
so i can got USA/CHT/CHS versions,it is enough.
I can build on HOST OS,the build SPEED is better.

**Comment by peter8777555** [comment]
Nice,
I  build in Windows XP English edtion and get ALL language versions.

So,Windows XP/7 Chinese edition can NOT to build.

**Comment by leecher1337** [comment]
Hopefully, the current commit fixes the buildmsg problem. May also be benificial to build performance, please check.

**Comment by peter8777555** [comment]
Windows 7 X64 Chinese Edtion : Failed.

BUILD: Done

    3804 files compiled - 402 Warnings - 245 Errors -  8453 LPS
    68 libraries built
    230 executables built - 2 Warnings
    721 files binplaced

[base.zip](https://github.com/leecher1337/ntvdmx64/files/4259258/base.zip)

**Comment by leecher1337** [comment]
I think I found tehe reason.
My CRLF conversion with
`more /p <%%f >tmp.msg`
is corrupting the file

**Comment by leecher1337** [comment]
Does it work now?

**Comment by peter8777555** [comment]
Great,it works and thank you a lot for working hard.

I have test in Windows XP Chinese edtion(Real PC).
I have test in Windows 7 X64 Chinese edtion(VMWare).

All of them get ALL language versions.

But it has one small error,it is not important.

BUILD: Done

    3920 files compiled - 398 Warnings - 2 Errors - 11437 LPS
    68 libraries built
    272 executables built - 2 Warnings
    811 files binplaced

4>NMAKE : fatal error U1077: 'cl16' : return code '0x2'
4>NMAKE : fatal error U1077: 'cl16' : return code '0x2'

[base.zip](https://github.com/leecher1337/ntvdmx64/files/4263495/base.zip)

**Comment by peter8777555** [comment]
By the way,
My old PC has use over 10 years and slow speed.
Host OS: Windows 7 X64.

For OLD NTVDMX64:
It just ONLY build in Windows XP (VMWare) and spend 1 hour.

For MinNT:
It build in Windows XP (VMWare) and spend  28 minutes.
It  build in Windows 7 X64 (Real PC) and spend 8 minutes.

It is good build speed on 8 minutes.

Thank you Sir.

**Comment by leecher1337** [comment]
I made an interesting observation runnign the cl16 line that fails in your build on CHT Windows 2000. It fails, if it is run on a default terminal with codepage 950 (due to charset conversion errors on compilation, I suppose).
But if I
`chcp 437`
before I run cl16, it runs through properly. So maybe you just need to chcp 437 your build console before you run bld-minnt ?

**Comment by peter8777555** [comment]
The code page 950 change to 437,the CMD window height will decrease.
No more 80x25 CMD Std. size.
It look strange.

**Comment by peter8777555** [comment]
I have one idea,
I want to run NTVDMX64  in Windows PE.
So, 
1. Make NTVDMX64  to portable and run in Windows PE.
2. Install NTVDMX64  and  run in Windows PE.

Which Option is possible ?

**Comment by leecher1337** [comment]
I think codepage change window size management is being done by conhost.exe console server, so I don't think that we can change this behaviour. There must be a reason behind this behaviour.

Regarding Windows PE, I don't know if it is possible to inject an AppInit DLL loader into Win PE. 

If it is a "frozen" system without future updates und there is no Patchgoard in PE, maybe Kernelbase etc. DLLs can be patched directly instead of doing a runtime patch like the loader does?
What is your usecase for NTVDMx64 in Win PE?

**Comment by peter8777555** [comment]
I just want to run old DOS exe for fun.

There are many many Windows PE on the internet,
They usually use pack/encrypt/compress/.... ,
I think to patch DLL directly,it is NOT good way.

If NTVDMx64  can run directly more better.
It like portable / inject /hook /.... 

I like your word:
"Microsoft was just too LAZY to port it over and have disabled it for unknown reasons."

**Comment by leecher1337** [comment]
I also enjoy running DOS applications of course, but I was just wondering what it is good for to pack it into a PE environment, because PE environment needs to be booted seperately, therefore, why use an emulated DOS in a PE environment and not just boot into real MS-DOS/Freedos in all its glory?

Btw.: Did you test if build completes with 100% success if you put `CHCP 437` in the second line of bld-minnt.cmd ? Because if this fixes the build process to reduce to 0 errors, I'd do a commit with this command enabled.

**Comment by peter8777555** [comment]
1.
Beginning:
Windows PE just for simple purpose only.

Now:
Many top one guys make Windows PE more powerful.
Windows PE can run AutoCad,PhotoShop,Office,surf web,play music/video/game,maintain,test,........
If DOS emulator inside Windows PE,
You boot Windows PE  only and get DOS + Windows application running.
This just a idea only.

2.
Amazing,
I add "chcp 437" in bld-minnt.cmd and build.
It got "0 Error" and mkrelease-minnt.bat got ALL language versions.

3926 files compiled - 398 Warnings -  8838 LPS
68 libraries built
274 executables built - 2 Warnings
815 files binplaced

**Comment by peter8777555** [comment]
By the way,

MinNT has multi-language versions.
I have one idea.
Can i change language versions ANYTIME ?

Step:
1. Normal Install C:\work\ntvdmpatch\releases\usa\dos\Install.bat
ReBoot
Now MinNT is USA version and work.

2.
Copy /Y C:\work\ntvdmpatch\releases\CHT\dos\*.* C:\Windows\System32
Copy /Y C:\work\ntvdmpatch\releases\CHT\dos\*.* C:\Windows\SysWOW64
Now MinNT is CHT version and work ?

**Comment by peter8777555** [comment]
![1](https://user-images.githubusercontent.com/29886853/75577904-e49bc300-5a9d-11ea-869e-4fa6a418945b.png)

**Comment by leecher1337** [comment]
If Win PE doesn't support AppInit Hooks (if it does, it should work there too), you can always try to use other hooking techniques like CreateProcess hookl. The loader code has a #define for it. When set, then it tries to propagate by hooking CreateProcess.

Regarding your question on changing the language version:
Theoretically, this should work. But be aware that, for example, Japanese build has additional drivers/files. So it has a different .inf as an installer. Now if you install USA build and then copy files from japanese build and then i.e. unstall NTVDMx64 via control panel, japanese files will be left over in system directory. Not a big deal, but just mentioning it.

**Comment by peter8777555** [comment]
So  hard link,
I just copy below only
Copy /Y C:\work\ntvdmpatch\releases\CHT\dos*.* C:\Windows\SysWOW64

**Comment by leecher1337** [comment]
correct

**Comment by peter8777555** [comment]
Because i compare with ALL language files.
All of them are the SAME.

**Comment by leecher1337** [comment]
What do you mean by that? Do you mean in the sourcecode? 
The .skl skeleton files are of course the came in every lang dir, but messages get inserted from .msg file on build.

**Comment by peter8777555** [comment]
I  mean C:\work\ntvdmpatch\releases\*.*

**Comment by leecher1337** [comment]
ntvdm.exe is mostly the same, all european languages have the same ntvdm.exe, but for example command.com is different depending on the language. Korea and Japan for instance have a different ntvdm.exe

**Comment by peter8777555** [comment]
JPN and KOR use special ntvdmx64.inf and ntvdmx64-32.inf

By the way,i surprise
I use
Windows XP English edtion
Windows XP Chinese edtion
Windows 7  Chinese edtion
to build

But get different binary files.

\dos\forcedos.exe
\dos\graftabl.com
\dos\ntvdm.exe
\dos\ntvdm.dll

About TimeDateStamp / ChckSum  / Some parts.

**Comment by leecher1337** [comment]
You have a build time timestamp in it, so it chances of course.
If you have different directories where you build the executable, you also get differences there because some assert()s include the full path of the source file as string.

**Comment by peter8777555** [comment]
>Seems like CmdBatNotification became a nullstub in more recent Win10 

I build and get "0 Error".
NTVDMX64 is stable now.

**Comment by dan4ikGit** [comment]
could somebody tell me please why prepare.bat says that minntfix doesn't exist? Or even better tell me what to do?

**Comment by leecher1337** [comment]
> could somebody tell me please why prepare.bat says that minntfix doesn't exist? Or even better tell me what to do?

Why not just use autobuild as documented?
