### ISSUE TITLE
Install.bat fails

### ISSUE THREAD

**Issue by PaoloRicardo** [leecher1337/ntvdmx64#79]
Running INSTALL.BAT I get :

C:\Users\paulr\Desktop\ntvdm64>install
---------------------------------------------
Checking machine
---------------------------------------------
'reg' is not recognized as an internal or external command,
operable program or batch file.

 presumably at this line:

echo ---------------------------------------------
echo Checking machine
echo ---------------------------------------------
reg query HKLM\Hardware\Description\System\CentralProcessor\0 | Find /i "x86" >nul

**Comment by leecher1337** [comment]
I suppose, your Windows installation is damaged or PETH environment is not setup correctly?
Windows should ship with reg.exe, it usually resides in %systemRoot%\system32 (i.e. c:\windows\system32)
I suggest that you restore the missing file from your Windows installation media, if it is missing.

https://answers.microsoft.com/en-us/windows/forum/all/cant-find-regexe-on-my-computer/fec6af7a-7fe2-40d0-8598-e29edfe8cd50

**Comment by PaoloRicardo** [comment]
Thanks. OK I amended the install.bat to read:

c:\windows\system32\reg query HKLM\Hardware\Description\System\CentralProcessor\0 | Find /i "x86" >nul

and I get:

'Find' is not recognized as an internal or external command,
operable program or batch file.

**Comment by PaoloRicardo** [comment]
I've modified my PATH variable to include c:\windows\system32. The batch file runs but I need to disable secure boot which I will now do. Thanks for the input.
