### ISSUE TITLE
Causes issue with SourceTree and git

### ISSUE THREAD

**Issue by kuenzign** [leecher1337/ntvdmx64#8]
When is have it installed, SourceTree using git is unable to pull and push correctly.  Pulling causes issues and pushing says that it was successful, but the origin remains unchanged.

**Comment by leecher1337** [comment]
Him
I updated the loader so that it hopefully doesn't interfere with CreateProcess() API anymore, please update your loader and try again.

**Comment by leecher1337** [comment]
N ofeedback given for over a year, therefore assuming it is fixed.
