### ISSUE TITLE
Select drag?

### ISSUE THREAD

**Issue by MeatPony** [leecher1337/ntvdmx64#80]
Is this supposed to happen?
![Select](https://user-images.githubusercontent.com/58016720/76388662-f9027a00-633f-11ea-9d01-7c1101df40a1.gif)
It occurred in some games I was playing too...

**Comment by leecher1337** [comment]
Hi,
this is normal Windows console behaviour. This is a standard Windows feature, you have to go to the properties fo your console window:
![image](https://user-images.githubusercontent.com/6495842/76394019-130a7f80-6375-11ea-9208-d89f797816f6.png)

Then turn off QuickEdit mode:
![image](https://user-images.githubusercontent.com/6495842/76393935-e35b7780-6374-11ea-834e-ab6ff56a4164.png)

**Comment by MeatPony** [comment]
thank you that fixed it
