### ISSUE TITLE
sizzle_minnt WARNING for 4/26/2020 version

### ISSUE THREAD

**Issue by peter8777555** [leecher1337/ntvdmx64#86]
It is OK to Build for 4/26/2020 version and got ALL release versions.

I got a warning,is this important or not ?

![1](https://user-images.githubusercontent.com/29886853/80456742-b41ebb00-8960-11ea-85cf-43d90ef038d0.png)

**Comment by leecher1337** [comment]
Normally, buildrepoidw -y should be done as specified in the tutorial to build IDW tools.
See build instructions Step 7:
https://github.com/leecher1337/ntvdmx64/blob/master/ntvdmpatch/doc/minnt.txt

**Comment by peter8777555** [comment]
I do not do step 7 "buildrepoidw -y" and it is OK to build.

Does Step 7 MUST to do ?

**Comment by leecher1337** [comment]
Once you did buildrepoidw the message normally vanishes for the next execution of the build shell (that's why -y is suggested in instructions, to ensure that it gets rebuilt even when there is no warning).

**Comment by peter8777555** [comment]
OK and thank you.
