### ISSUE TITLE
Error while setting up environment for the application

### ISSUE THREAD

**Issue by BubblyPopper** [leecher1337/ntvdmx64#89]
the error:
![pe](https://user-images.githubusercontent.com/41709262/81488802-d3e89580-9222-11ea-8a0d-1169d8930d58.PNG)
happens to me while trying to execute apps, example: pcman, hocus pocus game
h e l p n o w

**Comment by leecher1337** [comment]
Looks like 32bit Loaded from syswow64 directory isn't injected properly.
To diagnose the issue, try Process Explorer to check if ldntvdm.dll gets injected into 32bit Processes (including ntvdm.exe).
If ldntvdm.dll was injected properly, use Sysinternals DbgView to check for log messages of the loader.

**Comment by BubblyPopper** [comment]
wah wat? i am not experienced on this so i need you to explain me how to do that lol

**Comment by BubblyPopper** [comment]
i have process hacker, its similar to process explorer, but different

**Comment by leecher1337** [comment]
First ensure, that ldntvdm.dll is present in Windows\Syswow64 directory. Some stupid Antivirus applications tend to block it.

Next, download
https://docs.microsoft.com/en-us/sysinternals/downloads/debugview
and Capture Win32, start your DOS application and paste output here (ldntvdm tells you what it is doing during startup. If i.e. it cannot resolve Symbols from Microsoft Symbol server, it will tell you).

If NTVDM.exe is runnig and sitting there with the error message shown above, open Process explorer or Process hacker, go to the ntvdm.exe process and show its loaded Moduls (the DLLs it has in its address space, like kernel32.dll, ntdll.dll, etc.). Ensure, that ldntvdm.dll is also in that list.

**Comment by BubblyPopper** [comment]
OHHHHHHHHH

**Comment by BubblyPopper** [comment]
lol avast had deleted ldntvdm.dll
thanks for help
