### ISSUE TITLE
Work with programs that use other DLLs

### ISSUE THREAD

**Issue by LaserHack** [leecher1337/ntvdmx64#90]
I have old laser software that used VBRUN300.DLL would it be possible for this to work with programs that use other DLLs?
![2020-05-13](https://user-images.githubusercontent.com/17910612/81855674-a60a9600-952d-11ea-8380-01d23c4dce4c.png)

**Comment by leecher1337** [comment]
Looks like a Win16 application, not a DOS application.
Even though I'm currently working on WOW16 support (not sure if it is possible to get it running), I suggest you try WineVDM for Win16 applications: https://github.com/otya128/winevdm

**Comment by LaserHack** [comment]
Will repost there. Sorry for the error.
