### ISSUE TITLE
Windows XP x64 version

### ISSUE THREAD

**Issue by leecher1337** [leecher1337/ntvdmx64#94]
A user requested Windows XP x64 support for NTVDMx64

**Comment by AbdullahTrees** [comment]
Wait, does this mean you are working on it? It'd be cool though. This piques my interest cause I wonder whether the perfomance on 64-bit WinXP will be the same as 32-bit WinXP, or it will be the same as the performance on modern Win 7 and 10 64-bit OS's

**Comment by leecher1337** [comment]
I'm currently working on adapting the loader to Win XP/Server 2003 64bit, which is quite a lot of work because the inner-workings on these systems are different and lots of additional process-creation code needs to be added on thse systems compared to later Windows versions.

Don't expect any difference performance-wise compared to later Windows-Versions, CCPU isn't faster just because it runs on an old Windows version. If you want better performance and don't need DPMI and graphics, you can try the HAXM builds.

**Comment by leecher1337** [comment]
Windows Server 2003 x64 version works, no need for this ticket anymore.
