### ISSUE TITLE
Getting error loading 80's BBS in local mode 

### ISSUE THREAD

**Issue by richorr** [leecher1337/ntvdmx64#98]
I am trying to get an old 1980's BBS system (called Pyroto) stood up on a VM. It will run in VDOS but then can't be used as a BBS DOOR so I have pivoted to using ntvdmx64 on the advice from others in the community. 

I think it is installed correctly. I am seeing the ntvdm loading when I run the app in a console. When I look at it in DebugView, this is the error I am getting:
<img width="813" alt="Screen Shot 2020-06-26 at 2 43 16 PM" src="https://user-images.githubusercontent.com/5133207/85903583-8072dc80-b7bb-11ea-8765-3ab154aea8ca.png">

I get this same error when trying it without ntvdmx as well so I suspect there is something going on with the emulation. This same error doesn't occur in VDOS but the same error occurs with a default CMD window)

Here is a better screenshot of the load issue. It bails out with a Turbo Pascal Error 03:
<img width="441" alt="Screen Shot 2020-06-26 at 2 47 57 PM" src="https://user-images.githubusercontent.com/5133207/85903798-127ae500-b7bc-11ea-9d2f-c29ba6d32093.png">

**Comment by leecher1337** [comment]
So, do I understand correctly: NTVDM launches your DOS program just fine, but the DOS program spits out an error 03, so there is no issue with the loader, but with the FPU emulation, i.e. the DOS application raises an FPU error, possibly to invalid input data to the sqrt function. 
So if you launch other DOS applications, like, i.e. edit or qbasic, it starts up fine, just your BBS door is throwing an error?

So it needs to be debugged. Can you attach the application here and can it be started as standalone so that it can be analyzed? Or is even sourcecode available for it?

**Comment by richorr** [comment]
Yes, it certainly looks like FPU emulation. Interestingly unaltered CMD has this issue, and I also discovered tonight that DosBox throws the same error as well. The only system that doesn't throw the error is VDOS. 

I don't have source code, but I have attached a zip with the program. Run PYROTO LOCAL for it to start up. 
[PYROTO.zip](https://github.com/leecher1337/ntvdmx64/files/4840108/PYROTO.zip)

**Comment by leecher1337** [comment]
Runtime error 003 is "file not Found".
Are you sure that you are starting it from
C:\PYROTO ?
It runs fine here from that directory.

**Comment by richorr** [comment]
You are 100% correct (and my apologies for mis-diagnosing). I had it in a sub-directory while testing a different emulator and that clearly messed it up. Thank you!

**Comment by richorr** [comment]
...and thank you! This has been a vacation passion project. It took its first remote call this morning. 

<img width="610" alt="Screen Shot 2020-06-27 at 10 53 18 AM" src="https://user-images.githubusercontent.com/5133207/85928842-0bf47800-b865-11ea-93f9-663dfd9b815c.png">
<img width="643" alt="Screen Shot 2020-06-27 at 10 53 34 AM" src="https://user-images.githubusercontent.com/5133207/85928847-0f87ff00-b865-11ea-898b-dc4a45e2a4f6.png">
