### ISSUE TITLE
How can i know the 128 MB of DMPI mem ?

### ISSUE THREAD

**Issue by peter8777555** [leecher1337/ntvdmx64#99]
I have build the

2020/07/07  AM 05:45         2,341,130 ntvdmx64-master.zip

I import the dpmimem.reg
"DPMIMEM"="131070"

How can i know the 128 MB of DMPI mem ?

![123](https://user-images.githubusercontent.com/29886853/86867757-f6553d00-c105-11ea-9beb-4504bbf481ea.png)

**Comment by leecher1337** [comment]
You can see available DPMI mem on NTVDM initial startup via Debugview.
You should see:

```[3812] NTVDM: 147454K Memory: 15360K XMS, 0K EMS, 131070K DPMI```

**Comment by peter8777555** [comment]
Yes.I have checked.

Thank you.

![1222](https://user-images.githubusercontent.com/29886853/86938432-01928200-c173-11ea-916b-f18e495ccc41.png)

**Comment by leecher1337** [comment]
Iirc, DOOM and BLOOD need at least 16MB DPMI mem, but the real memory hungry DPMI application is DJGPP, 16MB isn't sufficient for it to even compile a simple "Hello World"
